const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/seedTaxa.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newTaxa = [
  // 1. Polypteridae & Polypterus
  {
    id: "taxon-polypteridae",
    scientificName: "Polypteridae",
    name: "Polypteridae",
    rank: "family",
    parentTaxonId: "taxon-polypteriformes",
    parentId: "taxon-polypteriformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1835",
    commonNameEn: "Bichirs and Reedfishes",
    commonNameBn: "বিচির ও রিডফিশ গোত্র",
    banglaName: "বিচির গোত্র",
    description: "Ancient basal ray-finned fish family characterized by thick ganoid scales, multiple dorsal finlets, and paired lung-like swim bladders.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)", citation: "Fishes of the World (5th ed.)" }]
  },
  {
    id: "taxon-polypterus",
    scientificName: "Polypterus",
    name: "Polypterus",
    rank: "genus",
    parentTaxonId: "taxon-polypteridae",
    parentId: "taxon-polypteridae",
    status: "accepted",
    module: "fish",
    authorYear: "Geoffroy Saint-Hilaire, 1802",
    commonNameEn: "Bichirs",
    commonNameBn: "বিচির গণ",
    banglaName: "বিচির",
    description: "Freshwater African genus of archaic bichirs with lobed pectoral fins and obligatory atmospheric air-breathing.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 2. Acipenseridae & Acipenser
  {
    id: "taxon-acipenseridae",
    scientificName: "Acipenseridae",
    name: "Acipenseridae",
    rank: "family",
    parentTaxonId: "taxon-acipenseriformes",
    parentId: "taxon-acipenseriformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1831",
    commonNameEn: "Sturgeons",
    commonNameBn: "স্টার্জন গোত্র",
    banglaName: "স্টার্জন গোত্র",
    description: "Primitive chondrostean fishes with five longitudinal rows of bony scutes, a largely cartilaginous endoskeleton, and four sensory barbels.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-acipenser",
    scientificName: "Acipenser",
    name: "Acipenser",
    rank: "genus",
    parentTaxonId: "taxon-acipenseridae",
    parentId: "taxon-acipenseridae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "True sturgeons",
    commonNameBn: "স্টার্জন গণ",
    banglaName: "স্টার্জন",
    description: "Anadromous and potamodromous sturgeon genus native to rivers and coastal waters of the Northern Hemisphere.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 3. Lepisosteidae & Atractosteus
  {
    id: "taxon-lepisosteidae",
    scientificName: "Lepisosteidae",
    name: "Lepisosteidae",
    rank: "family",
    parentTaxonId: "taxon-lepisosteiformes",
    parentId: "taxon-lepisosteiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Cuvier, 1825",
    commonNameEn: "Gars",
    commonNameBn: "গার গোত্র",
    banglaName: "গার গোত্র",
    description: "Holostean fish family with interlocking diamond-shaped ganoid scales, elongated jaws with sharp teeth, and vascularized swim bladders.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-atractosteus",
    scientificName: "Atractosteus",
    name: "Atractosteus",
    rank: "genus",
    parentTaxonId: "taxon-lepisosteidae",
    parentId: "taxon-lepisosteidae",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1820",
    commonNameEn: "Broad-snouted gars",
    commonNameBn: "বৃহৎ গার গণ",
    banglaName: "বৃহৎ গার",
    description: "Large predatory gar genus featuring two rows of enlarged teeth on the palatines in the upper jaw.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 4. Amiidae & Amia
  {
    id: "taxon-amiidae",
    scientificName: "Amiidae",
    name: "Amiidae",
    rank: "family",
    parentTaxonId: "taxon-amiiformes",
    parentId: "taxon-amiiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1831",
    commonNameEn: "Bowfins",
    commonNameBn: "বোফিন গোত্র",
    banglaName: "বোফিন গোত্র",
    description: "Archaic holostean family represented by modern bowfins, possessing an abbreviated heterocercal tail, median gular plate, and long dorsal fin.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-amia",
    scientificName: "Amia",
    name: "Amia",
    rank: "genus",
    parentTaxonId: "taxon-amiidae",
    parentId: "taxon-amiidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1766",
    commonNameEn: "Bowfin genus",
    commonNameBn: "বোফিন গণ",
    banglaName: "বোফিন",
    description: "Freshwater North American genus of predatory holostean fishes capable of atmospheric bimodal breathing.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 5. Anguillidae & Anguilla
  {
    id: "taxon-anguillidae",
    scientificName: "Anguillidae",
    name: "Anguillidae",
    rank: "family",
    parentTaxonId: "taxon-anguilliformes",
    parentId: "taxon-anguilliformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1810",
    commonNameEn: "Freshwater eels",
    commonNameBn: "মিঠাপানির বান মাছ গোত্র",
    banglaName: "আঙ্গুইলিডি",
    description: "Catadromous true eels possessing minute embedded cycloid scales, well-developed pectoral fins, and continuous dorsal-caudal-anal fins.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-anguilla",
    scientificName: "Anguilla",
    name: "Anguilla",
    rank: "genus",
    parentTaxonId: "taxon-anguillidae",
    parentId: "taxon-anguillidae",
    status: "accepted",
    module: "fish",
    authorYear: "Schrank, 1798",
    commonNameEn: "Freshwater eels genus",
    commonNameBn: "বান মাছ গণ",
    banglaName: "আঙ্গুইলা",
    description: "Catadromous genus migrating from continental rivers to oceanic abyssopelagic gyres to spawn leptocephalus larvae.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 6. Gymnotidae & Electrophorus
  {
    id: "taxon-gymnotidae",
    scientificName: "Gymnotidae",
    name: "Gymnotidae",
    rank: "family",
    parentTaxonId: "taxon-gymnotiformes",
    parentId: "taxon-gymnotiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1815",
    commonNameEn: "Naked-back knifefishes and Electric eels",
    commonNameBn: "বৈদ্যুতিক ইল গোত্র",
    banglaName: "জিমনোটিডি",
    description: "Neotropical electrogenic knifefishes lacking dorsal and pelvic fins, swimming by continuous undulating motion of an elongated anal fin.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-electrophorus",
    scientificName: "Electrophorus",
    name: "Electrophorus",
    rank: "genus",
    parentTaxonId: "taxon-gymnotidae",
    parentId: "taxon-gymnotidae",
    status: "accepted",
    module: "fish",
    authorYear: "Gill, 1864",
    commonNameEn: "Electric eels",
    commonNameBn: "বৈদ্যুতিক ইল গণ",
    banglaName: "ইলেক্ট্রোফোরাস",
    description: "Apex predator genus of South America equipped with three specialized bioelectric organs capable of generating up to 860 volts of discharge.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 7. Salmonidae & Salmo
  {
    id: "taxon-salmonidae",
    scientificName: "Salmonidae",
    name: "Salmonidae",
    rank: "family",
    parentTaxonId: "taxon-salmoniformes",
    parentId: "taxon-salmoniformes",
    status: "accepted",
    module: "fish",
    authorYear: "Cuvier, 1816",
    commonNameEn: "Salmons, Trouts, and Chars",
    commonNameBn: "স্যামন ও ট্রাউট গোত্র",
    banglaName: "স্যামনিডি",
    description: "Coldwater freshwater and anadromous teleost family bearing an adipose fin, fleshy axillary pelvic process, and tetraploid evolutionary ancestry.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-salmo",
    scientificName: "Salmo",
    name: "Salmo",
    rank: "genus",
    parentTaxonId: "taxon-salmonidae",
    parentId: "taxon-salmonidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "Atlantic salmons and trouts",
    commonNameBn: "স্যামন গণ",
    banglaName: "সালমো",
    description: "Native Atlantic basin genus of renowned coldwater anadromous and potamodromous sport and commercial fishes.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 8. Serrasalmidae & Pygocentrus
  {
    id: "taxon-serrasalmidae",
    scientificName: "Serrasalmidae",
    name: "Serrasalmidae",
    rank: "family",
    parentTaxonId: "taxon-characiformes",
    parentId: "taxon-characiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bleeker, 1859",
    commonNameEn: "Piranhas and Pacus",
    commonNameBn: "পিরানহা ও পাকু গোত্র",
    banglaName: "সেরাসালমিডি",
    description: "Neotropical characiform family possessing compressed deep bodies, sharp abdominal serrae, and specialized tricuspid or interlocking blade-like dentition.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-pygocentrus",
    scientificName: "Pygocentrus",
    name: "Pygocentrus",
    rank: "genus",
    parentTaxonId: "taxon-serrasalmidae",
    parentId: "taxon-serrasalmidae",
    status: "accepted",
    module: "fish",
    authorYear: "Müller & Troschel, 1844",
    commonNameEn: "True piranhas",
    commonNameBn: "পিরানহা গণ",
    banglaName: "পাইগোসেন্ট্রাস",
    description: "Aggressive shoaling carnivore genus equipped with razor-sharp triangular unicuspid teeth and strong jaw musculature.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 9. Gadidae & Gadus
  {
    id: "taxon-gadidae",
    scientificName: "Gadidae",
    name: "Gadidae",
    rank: "family",
    parentTaxonId: "taxon-gadiformes",
    parentId: "taxon-gadiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1810",
    commonNameEn: "True cods",
    commonNameBn: "কড মাছ গোত্র",
    banglaName: "গ্যাডিডি",
    description: "Commercially preeminent cold temperate marine gadiform family typically possessing three dorsal fins, two anal fins, and a chin barbel.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-gadus",
    scientificName: "Gadus",
    name: "Gadus",
    rank: "genus",
    parentTaxonId: "taxon-gadidae",
    parentId: "taxon-gadidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "Cods",
    commonNameBn: "কড গণ",
    banglaName: "গ্যাডাস",
    description: "Demersal marine cod genus foundational to Northern Hemisphere fisheries and maritime economies.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 10. Syngnathidae & Hippocampus
  {
    id: "taxon-syngnathidae",
    scientificName: "Syngnathidae",
    name: "Syngnathidae",
    rank: "family",
    parentTaxonId: "taxon-syngnathiformes",
    parentId: "taxon-syngnathiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1831",
    commonNameEn: "Seahorses and Pipefishes",
    commonNameBn: "সিন্থিয়া বা সিনগ্নাথিডি গোত্র",
    banglaName: "সিনগ্নাথিডি",
    description: "Remarkable syngnathiform family encased in bony dermal armor rings, with fused tubular jaws for suction-feeding and exclusive male pregnancy.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-hippocampus",
    scientificName: "Hippocampus",
    name: "Hippocampus",
    rank: "genus",
    parentTaxonId: "taxon-syngnathidae",
    parentId: "taxon-syngnathidae",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1810",
    commonNameEn: "Seahorses",
    commonNameBn: "সি-হর্স / সিন্ধুঘোটক গণ",
    banglaName: "হিপ্পোক্যাম্পাস",
    description: "Marine genus displaying vertical upright posture, bent neck, prehensile tail, and male brood pouch for carrying embryonic young.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 11. Pleuronectidae & Platichthys
  {
    id: "taxon-pleuronectidae",
    scientificName: "Pleuronectidae",
    name: "Pleuronectidae",
    rank: "family",
    parentTaxonId: "taxon-pleuronectiformes",
    parentId: "taxon-pleuronectiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1815",
    commonNameEn: "Righteye flounders",
    commonNameBn: "রাইট-আই ফ্ল্যাটফিশ গোত্র",
    banglaName: "প্লিউরোনেক্টিডি",
    description: "Asymmetric benthic flatfish family in which both eyes migrate to the right side of the head during larval metamorphosis.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-platichthys",
    scientificName: "Platichthys",
    name: "Platichthys",
    rank: "genus",
    parentTaxonId: "taxon-pleuronectidae",
    parentId: "taxon-pleuronectidae",
    status: "accepted",
    module: "fish",
    authorYear: "Girard, 1854",
    commonNameEn: "European flounders",
    commonNameBn: "ফ্লাউন্ডার গণ",
    banglaName: "প্লাটিকথিস",
    description: "Euryhaline flatfish genus capable of extensive seasonal migrations between coastal estuaries and freshwater rivers.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 12. Tetraodontidae & Tetraodon
  {
    id: "taxon-tetraodontidae",
    scientificName: "Tetraodontidae",
    name: "Tetraodontidae",
    rank: "family",
    parentTaxonId: "taxon-tetraodontiformes",
    parentId: "taxon-tetraodontiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1832",
    commonNameEn: "Pufferfishes",
    commonNameBn: "পটকা মাছ গোত্র",
    banglaName: "টেট্রাওডন্টিডি",
    description: "Globally distributed pufferfish family possessing four fused beak-like teeth, distensible stomachs for water inflation, and potent neurotoxins.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-tetraodon",
    scientificName: "Tetraodon",
    name: "Tetraodon",
    rank: "genus",
    parentTaxonId: "taxon-tetraodontidae",
    parentId: "taxon-tetraodontidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "African freshwater puffers",
    commonNameBn: "টেট্রাওডন গণ",
    banglaName: "টেট্রাওডন",
    description: "Freshwater riverine genus of puffers native to tropical Africa, including the giant mbu puffer.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 13. Lamnidae & Carcharodon
  {
    id: "taxon-lamnidae",
    scientificName: "Lamnidae",
    name: "Lamnidae",
    rank: "family",
    parentTaxonId: "taxon-lamniformes",
    parentId: "taxon-lamniformes",
    status: "accepted",
    module: "fish",
    authorYear: "Müller & Henle, 1838",
    commonNameEn: "Mackerel sharks and White sharks",
    commonNameBn: "ল্যামনিডি হাঙ্গর গোত্র",
    banglaName: "ল্যামনিডি",
    description: "Apex predatory shark family possessing endothermic countercurrent heat-exchange rete mirabile, conical snouts, and crescentic caudal fins.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-carcharodon",
    scientificName: "Carcharodon",
    name: "Carcharodon",
    rank: "genus",
    parentTaxonId: "taxon-lamnidae",
    parentId: "taxon-lamnidae",
    status: "accepted",
    module: "fish",
    authorYear: "Smith, 1838",
    commonNameEn: "Great white sharks",
    commonNameBn: "হোয়াইট শার্ক গণ",
    banglaName: "কার্চারোডন",
    description: "Monotypic modern macro-predatory shark genus with large triangular serrated teeth adapted for marine mammal predation.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 14. Carcharhinidae & Galeocerdo
  {
    id: "taxon-carcharhinidae",
    scientificName: "Carcharhinidae",
    name: "Carcharhinidae",
    rank: "family",
    parentTaxonId: "taxon-carcharhiniformes",
    parentId: "taxon-carcharhiniformes",
    status: "accepted",
    module: "fish",
    authorYear: "Jordan & Evermann, 1896",
    commonNameEn: "Requiem sharks",
    commonNameBn: "রেকোয়েম হাঙ্গর গোত্র",
    banglaName: "কার্কারহিনিডি",
    description: "Dominant tropical and warm temperate marine apex shark family possessing nictitating lower eyelids, round eyes, and precaudal pits.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-galeocerdo",
    scientificName: "Galeocerdo",
    name: "Galeocerdo",
    rank: "genus",
    parentTaxonId: "taxon-carcharhinidae",
    parentId: "taxon-carcharhinidae",
    status: "accepted",
    module: "fish",
    authorYear: "Müller & Henle, 1837",
    commonNameEn: "Tiger sharks",
    commonNameBn: "বাঘা হাঙ্গর গণ",
    banglaName: "গ্যালিওসার্ডো",
    description: "Cosmopolitan marine macropredator genus featuring unique cockscomb-shaped serrated teeth and dark vertical flank tiger striping.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 15. Mobulidae & Mobula
  {
    id: "taxon-mobulidae",
    scientificName: "Mobulidae",
    name: "Mobulidae",
    rank: "family",
    parentTaxonId: "taxon-myliobatiformes",
    parentId: "taxon-myliobatiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Gill, 1893",
    commonNameEn: "Manta and Devil rays",
    commonNameBn: "মান্টা রে ও শাপলাপাতা মাছ গোত্র",
    banglaName: "মোবুলিডি",
    description: "Pelagic filter-feeding batoid family possessing cephalic lobes/horns for funneling zooplankton, wing-like pectoral discs, and reduced dentition.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-mobula",
    scientificName: "Mobula",
    name: "Mobula",
    rank: "genus",
    parentTaxonId: "taxon-mobulidae",
    parentId: "taxon-mobulidae",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1810",
    commonNameEn: "Manta and devil rays genus",
    commonNameBn: "মান্টা রে গণ",
    banglaName: "মোবুলা",
    description: "Circumglobal epipelagic ray genus including oceanic mantas, known for acrobatic breaches and massive brain-to-body mass ratios.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 16. Synodontidae & Synodus
  {
    id: "taxon-synodontidae",
    scientificName: "Synodontidae",
    name: "Synodontidae",
    rank: "family",
    parentTaxonId: "taxon-aulopiformes",
    parentId: "taxon-aulopiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Gill, 1861",
    commonNameEn: "Lizardfishes",
    commonNameBn: "টিকটিকি মাছ গোত্র",
    banglaName: "সিনোডন্টিডি",
    description: "Benthic marine aulopiform ambush predators with elongated cylindrical bodies, large mouths packed with sharp slender teeth even on the tongue.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-synodus",
    scientificName: "Synodus",
    name: "Synodus",
    rank: "genus",
    parentTaxonId: "taxon-synodontidae",
    parentId: "taxon-synodontidae",
    status: "accepted",
    module: "fish",
    authorYear: "Scopoli, 1777",
    commonNameEn: "Lizardfishes genus",
    commonNameBn: "টিকটিকি মাছ গণ",
    banglaName: "সিনোডাস",
    description: "Marine genus camouflage-adapted for resting on sandy and coral reef substrates to launch high-speed darting ambush strikes.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 17. Scombridae & Scomber
  {
    id: "taxon-scombridae",
    scientificName: "Scombridae",
    name: "Scombridae",
    rank: "family",
    parentTaxonId: "taxon-scombriformes",
    parentId: "taxon-scombriformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1815",
    commonNameEn: "Mackerels, Tunas, and Bonitos",
    commonNameBn: "ম্যাকারেল ও টুনা গোত্র",
    banglaName: "স্কমব্রিডি",
    description: "Hydrodynamic pelagic cruisers with series of detached finlets behind dorsal and anal fins, slender caudal peduncle with keels, and high aerobic capacity.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-scomber",
    scientificName: "Scomber",
    name: "Scomber",
    rank: "genus",
    parentTaxonId: "taxon-scombridae",
    parentId: "taxon-scombridae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "True mackerels",
    commonNameBn: "ম্যাকারেল গণ",
    banglaName: "স্কম্বার",
    description: "Fast-swimming epipelagic schooling mackerel genus with undulating dorsal vermiculations and oily nutritious flesh.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 18. Carangidae & Caranx
  {
    id: "taxon-carangidae",
    scientificName: "Carangidae",
    name: "Carangidae",
    rank: "family",
    parentTaxonId: "taxon-carangiformes",
    parentId: "taxon-carangiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1815",
    commonNameEn: "Jacks, Trevallies, and Scads",
    commonNameBn: "ট্রেভালি ও জ্যাক গোত্র",
    banglaName: "ক্যারানজিডি",
    description: "High-speed marine and estuarine predatory teleosts with laterally compressed bodies, slender caudal peduncles, and lateral line with modified scutes.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-caranx",
    scientificName: "Caranx",
    name: "Caranx",
    rank: "genus",
    parentTaxonId: "taxon-carangidae",
    parentId: "taxon-carangidae",
    status: "accepted",
    module: "fish",
    authorYear: "Lacépède, 1801",
    commonNameEn: "Jacks and Trevallies",
    commonNameBn: "ট্রেভালি গণ",
    banglaName: "ক্যারানক্স",
    description: "Powerful marine predator genus including giant trevallies, celebrated for hunting versatility and apex status on coral reefs.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 19. Arapaimidae & Arapaima
  {
    id: "taxon-arapaimidae",
    scientificName: "Arapaimidae",
    name: "Arapaimidae",
    rank: "family",
    parentTaxonId: "taxon-osteoglossiformes",
    parentId: "taxon-osteoglossiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Bonaparte, 1846",
    commonNameEn: "Bonytongues and Arapaimas",
    commonNameBn: "আরাপাইমা গোত্র",
    banglaName: "আরাপাইমিডি",
    description: "Basal osteoglossomorph family containing some of the largest freshwater teleosts, with bony toothed tongues and heavy mineralized armor scales.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-arapaima",
    scientificName: "Arapaima",
    name: "Arapaima",
    rank: "genus",
    parentTaxonId: "taxon-arapaimidae",
    parentId: "taxon-arapaimidae",
    status: "accepted",
    module: "fish",
    authorYear: "Müller, 1843",
    commonNameEn: "Pirarucus and Arapaimas",
    commonNameBn: "আরাপাইমা গণ",
    banglaName: "আরাপাইমা",
    description: "Megafaunal Amazonian freshwater genus possessing a lung-like labyrinthine swim bladder enabling obligate surface respiration.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 20. Exocoetidae & Exocoetus
  {
    id: "taxon-exocoetidae",
    scientificName: "Exocoetidae",
    name: "Exocoetidae",
    rank: "family",
    parentTaxonId: "taxon-beloniformes",
    parentId: "taxon-beloniformes",
    status: "accepted",
    module: "fish",
    authorYear: "Risso, 1827",
    commonNameEn: "Flyingfishes",
    commonNameBn: "উড়ুক্কু মাছ গোত্র",
    banglaName: "একসোকোটিডি",
    description: "Epipelagic marine beloniforms with enormously enlarged wing-like pectoral fins enabling sustained gliding flight over the ocean surface to evade predators.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-exocoetus",
    scientificName: "Exocoetus",
    name: "Exocoetus",
    rank: "genus",
    parentTaxonId: "taxon-exocoetidae",
    parentId: "taxon-exocoetidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "Two-wing flyingfishes",
    commonNameBn: "উড়ুক্কু মাছ গণ",
    banglaName: "একসোকোটাস",
    description: "Circumtropical flyingfish genus possessing two large pectoral wings, capable of gliding hundreds of meters above waves.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 21. Lophiidae & Lophius
  {
    id: "taxon-lophiidae",
    scientificName: "Lophiidae",
    name: "Lophiidae",
    rank: "family",
    parentTaxonId: "taxon-lophiiformes",
    parentId: "taxon-lophiiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Rafinesque, 1810",
    commonNameEn: "Goosefishes and Monkfishes",
    commonNameBn: "মাঙ্কফিশ গোত্র",
    banglaName: "লোফিইডি",
    description: "Benthic marine anglerfishes with enormous flattened heads, wide crescentic mouths bristling with depressible teeth, and a modified dorsal spine lure.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-lophius",
    scientificName: "Lophius",
    name: "Lophius",
    rank: "genus",
    parentTaxonId: "taxon-lophiidae",
    parentId: "taxon-lophiidae",
    status: "accepted",
    module: "fish",
    authorYear: "Linnaeus, 1758",
    commonNameEn: "Monkfishes and Anglers",
    commonNameBn: "মাঙ্কফিশ গণ",
    banglaName: "লোফিয়াস",
    description: "North Atlantic and Mediterranean benthic genus harvested commercially for high-value tail meat.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  },

  // 22. Engraulidae & Engraulis
  {
    id: "taxon-engraulidae",
    scientificName: "Engraulidae",
    name: "Engraulidae",
    rank: "family",
    parentTaxonId: "taxon-clupeiformes",
    parentId: "taxon-clupeiformes",
    status: "accepted",
    module: "fish",
    authorYear: "Gill, 1861",
    commonNameEn: "Anchovies",
    commonNameBn: "এঙ্কোভি গোত্র",
    banglaName: "এনগ্রাউলিডি",
    description: "Small translucent silvery clupeiform schooling fishes with an overhanging snout, extremely wide subterminal mouth, and high forage biomass.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Nelson et al. (2016)" }]
  },
  {
    id: "taxon-engraulis",
    scientificName: "Engraulis",
    name: "Engraulis",
    rank: "genus",
    parentTaxonId: "taxon-engraulidae",
    parentId: "taxon-engraulidae",
    status: "accepted",
    module: "fish",
    authorYear: "Cuvier, 1816",
    commonNameEn: "Anchovies genus",
    commonNameBn: "এঙ্কোভি গণ",
    banglaName: "এনগ্রাউলিস",
    description: "Globally distributed marine pelagic genus supporting massive commercial fisheries and pelagic trophic food chains.",
    speciesCount: 1,
    isVerified: true,
    sourceReferences: [{ source: "Eschmeyer (2026)" }]
  }
];

// Append before ];
const lastBracketIdx = content.lastIndexOf('];');
if (lastBracketIdx === -1) {
  console.error("Could not find ending '];' in seedTaxa.ts");
  process.exit(1);
}

const formattedNewTaxa = newTaxa.map(t => '  ' + JSON.stringify(t, null, 2).replace(/\n/g, '\n  ')).join(',\n');
const updatedContent = content.slice(0, lastBracketIdx) + ',\n' + formattedNewTaxa + '\n' + content.slice(lastBracketIdx);

fs.writeFileSync(filePath, updatedContent, 'utf8');
console.log(`Successfully added ${newTaxa.length} new intermediate family and genus taxa to seedTaxa.ts!`);
