// scripts/data_textbook_expansion.cjs
// Curated textbook and educationally iconic zoological species & taxonomy nodes
// Supporting MASTER-FIX-14: Global Taxonomic Depth & Textbook Priority

const TEXTBOOK_TAXA_NODES = [
  // --- ANNELIDA ---
  {
    id: 'taxon-lumbricidae',
    scientificName: 'Lumbricidae',
    name: 'Lumbricidae',
    rank: 'family',
    parentId: 'taxon-haplotaxida',
    parentTaxonId: 'taxon-haplotaxida',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'True earthworms',
    commonNameBn: 'আদর্শ কেঁচো গোত্র',
    description: 'Terrestrial oligochaete clitellate annelids with distinct hydrostatic body wall and glandular clitellum.',
    isVerified: true
  },
  {
    id: 'taxon-eisenia',
    scientificName: 'Eisenia',
    name: 'Eisenia',
    rank: 'genus',
    parentId: 'taxon-lumbricidae',
    parentTaxonId: 'taxon-lumbricidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Malm, 1877',
    commonNameEn: 'Compost earthworms',
    commonNameBn: 'কম্পোস্ট কেঁচো গণ',
    description: 'Epigeic composting earthworms widely utilized in vermiculture and soil ecology research.',
    isVerified: true
  },
  {
    id: 'taxon-sabellida',
    scientificName: 'Sabellida',
    name: 'Sabellida',
    rank: 'order',
    parentId: 'taxon-polychaeta',
    parentTaxonId: 'taxon-polychaeta',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Fauchald, 1977',
    commonNameEn: 'Fan worms and feather dusters',
    commonNameBn: 'পাখাযুক্ত সামুদ্রিক নালী-কৃমি বর্গ',
    description: 'Sedentary polychaete tube-dwelling worms possessing a prominent ciliated branchial radiolar crown.',
    isVerified: true
  },
  {
    id: 'taxon-sabellidae',
    scientificName: 'Sabellidae',
    name: 'Sabellidae',
    rank: 'family',
    parentId: 'taxon-sabellida',
    parentTaxonId: 'taxon-sabellida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Latreille, 1825',
    commonNameEn: 'Feather duster worms',
    commonNameBn: 'পালক-ঝাড়ু কৃমি পরিবার',
    description: 'Tube-building marine polychaetes lacking operculum and utilizing mucilaginous radioles for filter feeding.',
    isVerified: true
  },
  {
    id: 'taxon-sabella',
    scientificName: 'Sabella',
    name: 'Sabella',
    rank: 'genus',
    parentId: 'taxon-sabellidae',
    parentTaxonId: 'taxon-sabellidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1767',
    commonNameEn: 'Fanworms',
    commonNameBn: 'পাখা-কৃমি গণ',
    description: 'Large benthic tubiculous polychaetes with bilateral radiolar spirals.',
    isVerified: true
  },

  // --- MOLLUSCA ---
  {
    id: 'taxon-sepiida',
    scientificName: 'Sepiida',
    name: 'Sepiida',
    rank: 'order',
    parentId: 'taxon-cephalopoda',
    parentTaxonId: 'taxon-cephalopoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'de Blainville, 1824',
    commonNameEn: 'Cuttlefishes',
    commonNameBn: 'কাটলফিশ বর্গ',
    description: 'Decapodiform cephalopods possessing an internal calcified aragonitic porous cuttlebone and w-shaped pupils.',
    isVerified: true
  },
  {
    id: 'taxon-sepiidae',
    scientificName: 'Sepiidae',
    name: 'Sepiidae',
    rank: 'family',
    parentId: 'taxon-sepiida',
    parentTaxonId: 'taxon-sepiida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Leach, 1817',
    commonNameEn: 'True cuttlefishes',
    commonNameBn: 'আদর্শ কাটলফিশ পরিবার',
    description: 'Benthic cuttlefishes capable of instantaneous neuro-chromatophore physiological camouflage.',
    isVerified: true
  },
  {
    id: 'taxon-sepia',
    scientificName: 'Sepia',
    name: 'Sepia',
    rank: 'genus',
    parentId: 'taxon-sepiidae',
    parentTaxonId: 'taxon-sepiidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Common cuttlefishes',
    commonNameBn: 'কাটলফিশ গণ',
    description: 'Archetypal cuttlefish genus with high-acuity polarized vision and chitinous suckered tentacular arms.',
    isVerified: true
  },
  {
    id: 'taxon-myopsida',
    scientificName: 'Myopsida',
    name: 'Myopsida',
    rank: 'order',
    parentId: 'taxon-cephalopoda',
    parentTaxonId: 'taxon-cephalopoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'd\'Orbigny, 1841',
    commonNameEn: 'Inshore squids',
    commonNameBn: 'উপকূলীয় স্কুইড বর্গ',
    description: 'Pelagic decapodiformes possessing eyes covered by a corneal membrane and eight arms plus two feeding tentacles.',
    isVerified: true
  },
  {
    id: 'taxon-loliginidae',
    scientificName: 'Loliginidae',
    name: 'Loliginidae',
    rank: 'family',
    parentId: 'taxon-myopsida',
    parentTaxonId: 'taxon-myopsida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Lesueur, 1821',
    commonNameEn: 'Pencil squids',
    commonNameBn: 'পেন্সিল স্কুইড পরিবার',
    description: 'Commercially vital inshore squids with elongate torpedo-like mantle and terminal lateral fins.',
    isVerified: true
  },
  {
    id: 'taxon-loligo',
    scientificName: 'Loligo',
    name: 'Loligo',
    rank: 'genus',
    parentId: 'taxon-loliginidae',
    parentTaxonId: 'taxon-loliginidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Lamarck, 1798',
    commonNameEn: 'Common squids',
    commonNameBn: 'স্কুইড গণ',
    description: 'Textbook cephalopod dissection genus possessing giant axon system historic to neurobiology.',
    isVerified: true
  },
  {
    id: 'taxon-pectinida',
    scientificName: 'Pectinida',
    name: 'Pectinida',
    rank: 'order',
    parentId: 'taxon-bivalvia',
    parentTaxonId: 'taxon-bivalvia',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1854',
    commonNameEn: 'Scallops and allies',
    commonNameBn: 'ঝিনুক স্কেলাপ বর্গ',
    description: 'Epifaunal and swimming bivalves with single large adductor muscle and numerous mantle photoreceptors.',
    isVerified: true
  },
  {
    id: 'taxon-pectinidae',
    scientificName: 'Pectinidae',
    name: 'Pectinidae',
    rank: 'family',
    parentId: 'taxon-pectinida',
    parentTaxonId: 'taxon-pectinida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'True scallops',
    commonNameBn: 'স্কেলাপ পরিবার',
    description: 'Fan-shaped bivalves capable of jet propulsion swimming by rapid shell clapping.',
    isVerified: true
  },
  {
    id: 'taxon-pecten',
    scientificName: 'Pecten',
    name: 'Pecten',
    rank: 'genus',
    parentId: 'taxon-pectinidae',
    parentTaxonId: 'taxon-pectinidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'O. F. Müller, 1776',
    commonNameEn: 'Scallops',
    commonNameBn: 'স্কেলাপ গণ',
    description: 'Classic textbook bivalve with radiating ribbed valve margins and sensory mantle eyes.',
    isVerified: true
  },
  {
    id: 'taxon-limacidae',
    scientificName: 'Limacidae',
    name: 'Limacidae',
    rank: 'family',
    parentId: 'taxon-stylommatophora',
    parentTaxonId: 'taxon-stylommatophora',
    status: 'accepted',
    module: 'general',
    authorYear: 'Lamarck, 1801',
    commonNameEn: 'Keelback slugs',
    commonNameBn: 'স্থলজ স্লাগ পরিবার',
    description: 'Air-breathing pulmonate terrestrial gastropods with shell internalized to a vestigial calcified plate.',
    isVerified: true
  },
  {
    id: 'taxon-limax',
    scientificName: 'Limax',
    name: 'Limax',
    rank: 'genus',
    parentId: 'taxon-limacidae',
    parentTaxonId: 'taxon-limacidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Leopard slugs',
    commonNameBn: 'চিতাবাঘ স্লাগ গণ',
    description: 'Large omnivorous nocturnal terrestrial pulmonates featuring aerial courtship suspended by mucus cords.',
    isVerified: true
  },

  // --- ARTHROPODA ---
  {
    id: 'taxon-scorpiones',
    scientificName: 'Scorpiones',
    name: 'Scorpiones',
    rank: 'order',
    parentId: 'taxon-arachnida',
    parentTaxonId: 'taxon-arachnida',
    status: 'accepted',
    module: 'general',
    authorYear: 'C. L. Koch, 1837',
    commonNameEn: 'Scorpions',
    commonNameBn: 'বিচ্ছু বা কাঁকড়াবিছা বর্গ',
    description: 'Arachnids with grasping chelate pedipalps and narrow segmented metasoma terminating in a venomous telson.',
    isVerified: true
  },
  {
    id: 'taxon-scorpionidae',
    scientificName: 'Scorpionidae',
    name: 'Scorpionidae',
    rank: 'family',
    parentId: 'taxon-scorpiones',
    parentTaxonId: 'taxon-scorpiones',
    status: 'accepted',
    module: 'general',
    authorYear: 'Latreille, 1802',
    commonNameEn: 'Burrowing scorpions',
    commonNameBn: 'গর্তজীবী বিচ্ছু পরিবার',
    description: 'Robust scorpions with massive crab-like pedipalp claws and strong fossorial legs.',
    isVerified: true
  },
  {
    id: 'taxon-pandinus',
    scientificName: 'Pandinus',
    name: 'Pandinus',
    rank: 'genus',
    parentId: 'taxon-scorpionidae',
    parentTaxonId: 'taxon-scorpionidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Thorell, 1876',
    commonNameEn: 'Emperor scorpions',
    commonNameBn: 'সম্রাট বিচ্ছু গণ',
    description: 'Giant African rainforest scorpions exhibiting brilliant cyan UV fluorescence.',
    isVerified: true
  },
  {
    id: 'taxon-branchiopoda',
    scientificName: 'Branchiopoda',
    name: 'Branchiopoda',
    rank: 'class',
    parentId: 'taxon-arthropoda',
    parentTaxonId: 'taxon-arthropoda',
    status: 'accepted',
    module: 'general',
    authorYear: 'Latreille, 1817',
    commonNameEn: 'Branchiopods and water fleas',
    commonNameBn: 'ব্রাঙ্কিওপড ক্রাস্টেসিয়ান শ্রেণি',
    description: 'Freshwater crustaceans with leaf-like (phyllopodous) thoracic appendages serving both gas exchange and filter-feeding.',
    isVerified: true
  },
  {
    id: 'taxon-anomopoda',
    scientificName: 'Anomopoda',
    name: 'Anomopoda',
    rank: 'order',
    parentId: 'taxon-branchiopoda',
    parentTaxonId: 'taxon-branchiopoda',
    status: 'accepted',
    module: 'general',
    authorYear: 'Sars, 1865',
    commonNameEn: 'Water fleas',
    commonNameBn: 'জলের মাছি বর্গ',
    description: 'Microscopic bivalved carapace planktonic crustaceans with large compound eye and swimming antennae.',
    isVerified: true
  },
  {
    id: 'taxon-daphniidae',
    scientificName: 'Daphniidae',
    name: 'Daphniidae',
    rank: 'family',
    parentId: 'taxon-anomopoda',
    parentTaxonId: 'taxon-anomopoda',
    status: 'accepted',
    module: 'general',
    authorYear: 'Straus, 1820',
    commonNameEn: 'Common water fleas',
    commonNameBn: 'ডাফনিয়া পরিবার',
    description: 'Cyclical parthenogens forming vital trophic base in limnetic freshwater ecosystems worldwide.',
    isVerified: true
  },
  {
    id: 'taxon-daphnia',
    scientificName: 'Daphnia',
    name: 'Daphnia',
    rank: 'genus',
    parentId: 'taxon-daphniidae',
    parentTaxonId: 'taxon-daphniidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'O. F. Müller, 1785',
    commonNameEn: 'Daphnia water fleas',
    commonNameBn: 'ডাফনিয়া গণ',
    description: 'Premier model organism in ecotoxicology, developmental biology, and phenotypic plasticity.',
    isVerified: true
  },
  {
    id: 'taxon-blattodea',
    scientificName: 'Blattodea',
    name: 'Blattodea',
    rank: 'order',
    parentId: 'taxon-insecta',
    parentTaxonId: 'taxon-insecta',
    status: 'accepted',
    module: 'general',
    authorYear: 'Brunner von Wattenwyl, 1882',
    commonNameEn: 'Cockroaches and termites',
    commonNameBn: 'আরশোলা ও উইপোকা বর্গ',
    description: 'Hemimetabolous neopteran insects with flattened dorsoventral body, shielding pronotum, and cerci.',
    isVerified: true
  },
  {
    id: 'taxon-blattidae',
    scientificName: 'Blattidae',
    name: 'Blattidae',
    rank: 'family',
    parentId: 'taxon-blattodea',
    parentTaxonId: 'taxon-blattodea',
    status: 'accepted',
    module: 'general',
    authorYear: 'Latreille, 1810',
    commonNameEn: 'True cockroaches',
    commonNameBn: 'আদর্শ আরশোলা পরিবার',
    description: 'Cosmopolitan synanthropic cockroaches with cursorial spiny legs and omnivorous chewing mouthparts.',
    isVerified: true
  },
  {
    id: 'taxon-periplaneta',
    scientificName: 'Periplaneta',
    name: 'Periplaneta',
    rank: 'genus',
    parentId: 'taxon-blattidae',
    parentTaxonId: 'taxon-blattidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Burmeister, 1838',
    commonNameEn: 'American cockroaches',
    commonNameBn: 'তেলাপোকা গণ',
    description: 'The standard textbook insect dissection and neurophysiology laboratory subject globally.',
    isVerified: true
  },
  {
    id: 'taxon-drosophilidae',
    scientificName: 'Drosophilidae',
    name: 'Drosophilidae',
    rank: 'family',
    parentId: 'taxon-diptera',
    parentTaxonId: 'taxon-diptera',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rondani, 1856',
    commonNameEn: 'Fruit flies and vinegar flies',
    commonNameBn: 'ফল মাছি পরিবার',
    description: 'Small acalyptrate dipterans feeding on fermenting fruit, yeasts, and sap exudates.',
    isVerified: true
  },
  {
    id: 'taxon-drosophila',
    scientificName: 'Drosophila',
    name: 'Drosophila',
    rank: 'genus',
    parentId: 'taxon-drosophilidae',
    parentTaxonId: 'taxon-drosophilidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fallén, 1823',
    commonNameEn: 'Model fruit flies',
    commonNameBn: 'ড্রসোফিলা গণ',
    description: 'The paramount genetic and developmental model organism in modern biological science.',
    isVerified: true
  },
  {
    id: 'taxon-odonata',
    scientificName: 'Odonata',
    name: 'Odonata',
    rank: 'order',
    parentId: 'taxon-insecta',
    parentTaxonId: 'taxon-insecta',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fabricius, 1793',
    commonNameEn: 'Dragonflies and damselflies',
    commonNameBn: 'ফড়িং ও ড্যামসেলফ্লাই বর্গ',
    description: 'Paleopterous aerial predatory insects with multifacetted compound eyes and aquatic predatory naiads.',
    isVerified: true
  },
  {
    id: 'taxon-aeshnidae',
    scientificName: 'Aeshnidae',
    name: 'Aeshnidae',
    rank: 'family',
    parentId: 'taxon-odonata',
    parentTaxonId: 'taxon-odonata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rambur, 1842',
    commonNameEn: 'Darner dragonflies',
    commonNameBn: 'ডায়নামিক শিকারী ফড়িং পরিবার',
    description: 'Large swift-flying dragonflies with contiguous compound eyes and high aerial maneuverability.',
    isVerified: true
  },
  {
    id: 'taxon-anax',
    scientificName: 'Anax',
    name: 'Anax',
    rank: 'genus',
    parentId: 'taxon-aeshnidae',
    parentTaxonId: 'taxon-aeshnidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Leach, 1815',
    commonNameEn: 'Green darners',
    commonNameBn: 'সবুজ ডার্নার ফড়িং গণ',
    description: 'Iconic textbook migratory dragonfly genus with prehensile labial mask in aquatic nymphs.',
    isVerified: true
  },

  // --- CNIDARIA ---
  {
    id: 'taxon-anthoathecata',
    scientificName: 'Anthoathecata',
    name: 'Anthoathecata',
    rank: 'order',
    parentId: 'taxon-hydrozoa',
    parentTaxonId: 'taxon-hydrozoa',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cornelius, 1992',
    commonNameEn: 'Athecate hydroids and hydras',
    commonNameBn: 'অ্যাথেকেট হাইড্রয়েড বর্গ',
    description: 'Hydrozoans lacking rigid theca around hydranths; includes solitary freshwater polyps.',
    isVerified: true
  },
  {
    id: 'taxon-hydridae',
    scientificName: 'Hydridae',
    name: 'Hydridae',
    rank: 'family',
    parentId: 'taxon-anthoathecata',
    parentTaxonId: 'taxon-anthoathecata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Dana, 1846',
    commonNameEn: 'Hydras',
    commonNameBn: 'হাইড্রা পরিবার',
    description: 'Solitary freshwater polyps exhibiting stem cell-mediated continuous regeneration and budding.',
    isVerified: true
  },
  {
    id: 'taxon-hydra',
    scientificName: 'Hydra',
    name: 'Hydra',
    rank: 'genus',
    parentId: 'taxon-hydridae',
    parentTaxonId: 'taxon-hydridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Freshwater hydras',
    commonNameBn: 'মিঠাপানির হাইড্রা গণ',
    description: 'The universally standard school and university textbook cnidarian demonstrating tissue-grade diploblasty.',
    isVerified: true
  },
  {
    id: 'taxon-mussidae',
    scientificName: 'Mussidae',
    name: 'Mussidae',
    rank: 'family',
    parentId: 'taxon-scleractinia',
    parentTaxonId: 'taxon-scleractinia',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Ortmann, 1890',
    commonNameEn: 'Brain corals',
    commonNameBn: 'মস্তিষ্ক প্রবাল পরিবার',
    description: 'Massive reef-building scleractinian stony corals with meandroid valley-and-ridge corallite valleys.',
    isVerified: true
  },
  {
    id: 'taxon-diploria',
    scientificName: 'Diploria',
    name: 'Diploria',
    rank: 'genus',
    parentId: 'taxon-mussidae',
    parentTaxonId: 'taxon-mussidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Milne Edwards & Haime, 1848',
    commonNameEn: 'Grooved brain corals',
    commonNameBn: 'খাঁজযুক্ত মস্তিষ্ক প্রবাল গণ',
    description: 'Colonial zooxanthellate stony corals building massive hemispherical heads in tropical reefs.',
    isVerified: true
  },

  // --- PORIFERA ---
  {
    id: 'taxon-leucosoleniida',
    scientificName: 'Leucosoleniida',
    name: 'Leucosoleniida',
    rank: 'order',
    parentId: 'taxon-calcarea',
    parentTaxonId: 'taxon-calcarea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Hartman, 1958',
    commonNameEn: 'Asconoid calcareous sponges',
    commonNameBn: 'অ্যাসকনয়েড চুনযুক্ত স্পঞ্জ বর্গ',
    description: 'Primitive calcareous sponges with simplest asconoid tubular organization lacking choanocyte folding.',
    isVerified: true
  },
  {
    id: 'taxon-leucosoleniidae',
    scientificName: 'Leucosoleniidae',
    name: 'Leucosoleniidae',
    rank: 'family',
    parentId: 'taxon-leucosoleniida',
    parentTaxonId: 'taxon-leucosoleniida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Kölliker, 1864',
    commonNameEn: 'Leucosolenia sponges',
    commonNameBn: 'লিউকোসোলেনিয়া পরিবার',
    description: 'Branching networks of thin-walled asconoid tubes with simple oscular chimneys.',
    isVerified: true
  },
  {
    id: 'taxon-leucosolenia',
    scientificName: 'Leucosolenia',
    name: 'Leucosolenia',
    rank: 'genus',
    parentId: 'taxon-leucosoleniidae',
    parentTaxonId: 'taxon-leucosoleniidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Bowerbank, 1864',
    commonNameEn: 'White lace sponges',
    commonNameBn: 'লিউকোসোলেনিয়া গণ',
    description: 'The definitive textbook representative of the fundamental asconoid body construction in Metazoa.',
    isVerified: true
  },

  // --- CTENOPHORA ---
  {
    id: 'taxon-cestida',
    scientificName: 'Cestida',
    name: 'Cestida',
    rank: 'order',
    parentId: 'taxon-tentaculata',
    parentTaxonId: 'taxon-tentaculata',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gegenbaur, 1856',
    commonNameEn: 'Ribbon comb jellies',
    commonNameBn: 'ফিতাকৃতির কম্ব জেলি বর্গ',
    description: 'Pelagic tentaculate ctenophores extremely compressed in sagittal plane forming undulating ribbons up to 1.5 m long.',
    isVerified: true
  },
  {
    id: 'taxon-cestidae',
    scientificName: 'Cestidae',
    name: 'Cestidae',
    rank: 'family',
    parentId: 'taxon-cestida',
    parentTaxonId: 'taxon-cestida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gegenbaur, 1856',
    commonNameEn: 'Venus\' girdles',
    commonNameBn: 'ভেনাস গার্ডল পরিবার',
    description: 'Elongate ribbon-like ctenophores swimming with serpentine muscular undulations.',
    isVerified: true
  },
  {
    id: 'taxon-cestum',
    scientificName: 'Cestum',
    name: 'Cestum',
    rank: 'genus',
    parentId: 'taxon-cestidae',
    parentTaxonId: 'taxon-cestidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Lesueur, 1813',
    commonNameEn: 'Venus\' girdle ribbons',
    commonNameBn: 'ভেনাস গার্ডল গণ',
    description: 'Classic textbook ctenophore demonstrating extreme morphological radiation within Tentaculata.',
    isVerified: true
  },

  // --- ECHINODERMATA ---
  {
    id: 'taxon-asteriidae',
    scientificName: 'Asteriidae',
    name: 'Asteriidae',
    rank: 'family',
    parentId: 'taxon-forcipulatida',
    parentTaxonId: 'taxon-forcipulatida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1840',
    commonNameEn: 'Common sea stars',
    commonNameBn: 'আদর্শ তারা মাছ পরিবার',
    description: 'Forcipulate sea stars equipped with crossed and straight pedicellariae and eversible cardiac stomach.',
    isVerified: true
  },
  {
    id: 'taxon-asterias',
    scientificName: 'Asterias',
    name: 'Asterias',
    rank: 'genus',
    parentId: 'taxon-asteriidae',
    parentTaxonId: 'taxon-asteriidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Starfishes',
    commonNameBn: 'তারা মাছ গণ',
    description: 'The premier textbook dissection type representing water vascular system and pentaradial symmetry.',
    isVerified: true
  },
  {
    id: 'taxon-echinidae',
    scientificName: 'Echinidae',
    name: 'Echinidae',
    rank: 'family',
    parentId: 'taxon-camarodonta',
    parentTaxonId: 'taxon-camarodonta',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1825',
    commonNameEn: 'Edible sea urchins',
    commonNameBn: 'খাদ্যোপযোগী সামুদ্রিক আর্চিন পরিবার',
    description: 'Globular regular echinoids with rigid test and Aristotle\'s lantern equipped with keeled teeth.',
    isVerified: true
  },
  {
    id: 'taxon-echinus',
    scientificName: 'Echinus',
    name: 'Echinus',
    rank: 'genus',
    parentId: 'taxon-echinidae',
    parentTaxonId: 'taxon-echinidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'European sea urchins',
    commonNameBn: 'আর্চিন গণ',
    description: 'Historical textbook model organism for embryological cleavage and deuterostome fertilization experiments.',
    isVerified: true
  },
  {
    id: 'taxon-crinoidea',
    scientificName: 'Crinoidea',
    name: 'Crinoidea',
    rank: 'class',
    parentId: 'taxon-echinodermata',
    parentTaxonId: 'taxon-echinodermata',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Miller, 1821',
    commonNameEn: 'Sea lilies and feather stars',
    commonNameBn: 'পালক তারা ও সি-লিলি শ্রেণি',
    description: 'The most basal living echinoderm class; sessile stalked or motile unstalked suspension feeders with upward-facing mouth.',
    isVerified: true
  },
  {
    id: 'taxon-comatulida',
    scientificName: 'Comatulida',
    name: 'Comatulida',
    rank: 'order',
    parentId: 'taxon-crinoidea',
    parentTaxonId: 'taxon-crinoidea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'A. H. Clark, 1908',
    commonNameEn: 'Feather stars',
    commonNameBn: 'পালক তারা বর্গ',
    description: 'Free-living crinoids shedding larval stalk and swimming or crawling with branched pinnulate arms.',
    isVerified: true
  },
  {
    id: 'taxon-antedonidae',
    scientificName: 'Antedonidae',
    name: 'Antedonidae',
    rank: 'family',
    parentId: 'taxon-comatulida',
    parentTaxonId: 'taxon-comatulida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Norman, 1865',
    commonNameEn: 'Mediterranean feather stars',
    commonNameBn: 'অ্যান্টিডন পরিবার',
    description: 'Feather stars equipped with cirri on the centrodorsal plate and ten pinnulated flexible arms.',
    isVerified: true
  },
  {
    id: 'taxon-antedon',
    scientificName: 'Antedon',
    name: 'Antedon',
    rank: 'genus',
    parentId: 'taxon-antedonidae',
    parentTaxonId: 'taxon-antedonidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'de Fréminville, 1811',
    commonNameEn: 'Feather stars',
    commonNameBn: 'অ্যান্টিডন গণ',
    description: 'Textbook representative of Class Crinoidea illustrating the ancestral echinoderm ambulacral filter-feeding mechanism.',
    isVerified: true
  },

  // --- AMPHIBIA ---
  {
    id: 'taxon-ambystomatidae',
    scientificName: 'Ambystomatidae',
    name: 'Ambystomatidae',
    rank: 'family',
    parentId: 'taxon-caudata',
    parentTaxonId: 'taxon-caudata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1850',
    commonNameEn: 'Mole salamanders',
    commonNameBn: 'মোল স্যালামান্ডার পরিবার',
    description: 'Robust terrestrial and aquatic urodeles with costal grooves, internal fertilization, and frequent neoteny.',
    isVerified: true
  },
  {
    id: 'taxon-ambystoma',
    scientificName: 'Ambystoma',
    name: 'Ambystoma',
    rank: 'genus',
    parentId: 'taxon-ambystomatidae',
    parentTaxonId: 'taxon-ambystomatidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Tschudi, 1838',
    commonNameEn: 'Mole salamanders and axolotls',
    commonNameBn: 'অ্যাক্সোলটল গণ',
    description: 'Renowned worldwide in regenerative biology, genetics, and comparative vertebrate embryology.',
    isVerified: true
  },
  {
    id: 'taxon-dendrobatidae',
    scientificName: 'Dendrobatidae',
    name: 'Dendrobatidae',
    rank: 'family',
    parentId: 'taxon-anura',
    parentTaxonId: 'taxon-anura',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cope, 1865',
    commonNameEn: 'Poison dart frogs',
    commonNameBn: 'বিষাক্ত তীর ব্যাঙ পরিবার',
    description: 'Aposematically colored diurnal neotropical anurans sequestering potent batrachotoxin alkaloids.',
    isVerified: true
  },
  {
    id: 'taxon-dendrobates',
    scientificName: 'Dendrobates',
    name: 'Dendrobates',
    rank: 'genus',
    parentId: 'taxon-dendrobatidae',
    parentTaxonId: 'taxon-dendrobatidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Wagler, 1830',
    commonNameEn: 'Poison dart frogs',
    commonNameBn: 'তীর ব্যাঙ গণ',
    description: 'Classic textbook example of aposematism, warning coloration, and specialized parental care in amphibians.',
    isVerified: true
  },

  // --- REPTILIA ---
  {
    id: 'taxon-crocodilidae',
    scientificName: 'Crocodylidae',
    name: 'Crocodylidae',
    rank: 'family',
    parentId: 'taxon-crocodylia',
    parentTaxonId: 'taxon-crocodylia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cuvier, 1807',
    commonNameEn: 'True crocodiles',
    commonNameBn: 'প্রকৃত কুমির পরিবার',
    description: 'Large aquatic archosaurian reptiles with narrow triangular snout and interlocking lower 4th teeth.',
    isVerified: true
  },
  {
    id: 'taxon-crocodylus',
    scientificName: 'Crocodylus',
    name: 'Crocodylus',
    rank: 'genus',
    parentId: 'taxon-crocodilidae',
    parentTaxonId: 'taxon-crocodilidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Laurenti, 1768',
    commonNameEn: 'Crocodiles',
    commonNameBn: 'কুমির গণ',
    description: 'Apex amphibious predatory reptiles exhibiting sensory lingual salt glands and four-chambered hearts.',
    isVerified: true
  },
  {
    id: 'taxon-gavialidae',
    scientificName: 'Gavialidae',
    name: 'Gavialidae',
    rank: 'family',
    parentId: 'taxon-crocodylia',
    parentTaxonId: 'taxon-crocodylia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Adams, 1854',
    commonNameEn: 'Gharials and false gharials',
    commonNameBn: 'ঘড়িয়াল পরিবার',
    description: 'Specialized piscivorous crocodylians with extremely narrow elongate jaws lined with interlocking needle teeth.',
    isVerified: true
  },
  {
    id: 'taxon-gavialis',
    scientificName: 'Gavialis',
    name: 'Gavialis',
    rank: 'genus',
    parentId: 'taxon-gavialidae',
    parentTaxonId: 'taxon-gavialidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Oppel, 1811',
    commonNameEn: 'Fish-eating crocodiles',
    commonNameBn: 'ঘড়িয়াল গণ',
    description: 'Native to South Asian major river systems (including historical Padma/Meghna in Bangladesh); bulbous ghara on mature males.',
    isVerified: true
  },
  {
    id: 'taxon-naja',
    scientificName: 'Naja',
    name: 'Naja',
    rank: 'genus',
    parentId: 'taxon-elapidae',
    parentTaxonId: 'taxon-elapidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Laurenti, 1768',
    commonNameEn: 'True cobras',
    commonNameBn: 'গোখরা গণ',
    description: 'Proteroglyphous elapid snakes with expandable cervical ribs producing the defensive hood and potent post-synaptic neurotoxin.',
    isVerified: true
  },
  {
    id: 'taxon-chamaeleonidae',
    scientificName: 'Chamaeleonidae',
    name: 'Chamaeleonidae',
    rank: 'family',
    parentId: 'taxon-squamata',
    parentTaxonId: 'taxon-squamata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1825',
    commonNameEn: 'Chameleons',
    commonNameBn: 'গিরগিটি বা ক্যামেলিয়ন পরিবার',
    description: 'Specialized arboreal squamates with zygodactylous feet, independently mobile stereoscopic eyes, prehensile tail, and ballistic tongue.',
    isVerified: true
  },
  {
    id: 'taxon-chamaeleo',
    scientificName: 'Chamaeleo',
    name: 'Chamaeleo',
    rank: 'genus',
    parentId: 'taxon-chamaeleonidae',
    parentTaxonId: 'taxon-chamaeleonidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Laurenti, 1768',
    commonNameEn: 'Typical chameleons',
    commonNameBn: 'ক্যামেলিয়ন গণ',
    description: 'Archetypal textbook lizard demonstrating structural crystal-mediated color change and ballistic tongue projection.',
    isVerified: true
  },

  // --- AVES ---
  {
    id: 'taxon-columbiformes',
    scientificName: 'Columbiformes',
    name: 'Columbiformes',
    rank: 'order',
    parentId: 'taxon-aves',
    parentTaxonId: 'taxon-aves',
    status: 'accepted',
    module: 'general',
    authorYear: 'Latham, 1790',
    commonNameEn: 'Pigeons and doves',
    commonNameBn: 'কবুতর ও ঘুঘু বর্গ',
    description: 'Stout-bodied birds with short necks, fleshy cere, and specialized esophageal crop producing crop milk.',
    isVerified: true
  },
  {
    id: 'taxon-columbidae',
    scientificName: 'Columbidae',
    name: 'Columbidae',
    rank: 'family',
    parentId: 'taxon-columbiformes',
    parentTaxonId: 'taxon-columbiformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Leach, 1820',
    commonNameEn: 'Pigeons and doves',
    commonNameBn: 'কবুতর পরিবার',
    description: 'Cosmopolitan granivorous and frugivorous birds with powerful flight pectoral musculature.',
    isVerified: true
  },
  {
    id: 'taxon-columba',
    scientificName: 'Columba',
    name: 'Columba',
    rank: 'genus',
    parentId: 'taxon-columbidae',
    parentTaxonId: 'taxon-columbidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Pigeons',
    commonNameBn: 'কবুতর গণ',
    description: 'The universal textbook bird dissection and avian physiology model organism worldwide.',
    isVerified: true
  },
  {
    id: 'taxon-galliformes',
    scientificName: 'Galliformes',
    name: 'Galliformes',
    rank: 'order',
    parentId: 'taxon-aves',
    parentTaxonId: 'taxon-aves',
    status: 'accepted',
    module: 'general',
    authorYear: 'Temminck, 1820',
    commonNameEn: 'Gamefowl and pheasants',
    commonNameBn: 'মুরগি ও তিতির বর্গ',
    description: 'Heavy-bodied ground-feeding birds with blunt wings, strong scratching feet, and precocial chicks.',
    isVerified: true
  },
  {
    id: 'taxon-phasianidae',
    scientificName: 'Phasianidae',
    name: 'Phasianidae',
    rank: 'family',
    parentId: 'taxon-galliformes',
    parentTaxonId: 'taxon-galliformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Horsfield, 1821',
    commonNameEn: 'Pheasants, junglefowl, and peafowl',
    commonNameBn: 'ময়ূর ও বনমোরগ পরিবার',
    description: 'Ground birds exhibiting pronounced sexual dimorphism, spurs on tarsi, and elaborate male displays.',
    isVerified: true
  },
  {
    id: 'taxon-gallus',
    scientificName: 'Gallus',
    name: 'Gallus',
    rank: 'genus',
    parentId: 'taxon-phasianidae',
    parentTaxonId: 'taxon-phasianidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Brisson, 1760',
    commonNameEn: 'Junglefowl and chickens',
    commonNameBn: 'বনমোরগ গণ',
    description: 'Ancestral genus of the domestic chicken and primary experimental model in developmental embryology.',
    isVerified: true
  },
  {
    id: 'taxon-pavo',
    scientificName: 'Pavo',
    name: 'Pavo',
    rank: 'genus',
    parentId: 'taxon-phasianidae',
    parentTaxonId: 'taxon-phasianidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Peafowl',
    commonNameBn: 'ময়ূর গণ',
    description: 'Iconic Asian birds demonstrating extreme sexual selection via iridescent elongated upper tail covert trains.',
    isVerified: true
  },
  {
    id: 'taxon-passeridae',
    scientificName: 'Passeridae',
    name: 'Passeridae',
    rank: 'family',
    parentId: 'taxon-passeriformes',
    parentTaxonId: 'taxon-passeriformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'Old World sparrows',
    commonNameBn: 'চড়ুই পরিবার',
    description: 'Small granivorous passerines with conical seed-cracking bills and high sociability.',
    isVerified: true
  },
  {
    id: 'taxon-passer',
    scientificName: 'Passer',
    name: 'Passer',
    rank: 'genus',
    parentId: 'taxon-passeridae',
    parentTaxonId: 'taxon-passeridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Brisson, 1760',
    commonNameEn: 'True sparrows',
    commonNameBn: 'চড়ুই গণ',
    description: 'Ubiquitous synanthropic birds familiar to millions worldwide across school and university biology curricula.',
    isVerified: true
  },
  {
    id: 'taxon-corvidae',
    scientificName: 'Corvidae',
    name: 'Corvidae',
    rank: 'family',
    parentId: 'taxon-passeriformes',
    parentTaxonId: 'taxon-passeriformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Leach, 1820',
    commonNameEn: 'Crows, ravens, and jays',
    commonNameBn: 'কাক পরিবার',
    description: 'Highly intelligent oscine passerines with massive brain-to-body ratios and advanced tool use.',
    isVerified: true
  },
  {
    id: 'taxon-corvus',
    scientificName: 'Corvus',
    name: 'Corvus',
    rank: 'genus',
    parentId: 'taxon-corvidae',
    parentTaxonId: 'taxon-corvidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Crows and ravens',
    commonNameBn: 'কাক গণ',
    description: 'The standard textbook representative of avian cognitive intelligence and behavioral plasticity.',
    isVerified: true
  },
  {
    id: 'taxon-phoenicopteriformes',
    scientificName: 'Phoenicopteriformes',
    name: 'Phoenicopteriformes',
    rank: 'order',
    parentId: 'taxon-aves',
    parentTaxonId: 'taxon-aves',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fürbringer, 1888',
    commonNameEn: 'Flamingos',
    commonNameBn: 'ফ্ল্যামিঙ্গো বর্গ',
    description: 'Long-legged wading birds with specialized down-bent lamellar filter-feeding bill and pink carotenoid plumage.',
    isVerified: true
  },
  {
    id: 'taxon-phoenicopteridae',
    scientificName: 'Phoenicopteridae',
    name: 'Phoenicopteridae',
    rank: 'family',
    parentId: 'taxon-phoenicopteriformes',
    parentTaxonId: 'taxon-phoenicopteriformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Bonaparte, 1831',
    commonNameEn: 'True flamingos',
    commonNameBn: 'ফ্ল্যামিঙ্গো পরিবার',
    description: 'Colonial saline and alkaline lake wading birds filter-feeding microscopic algae and brine shrimp.',
    isVerified: true
  },
  {
    id: 'taxon-phoenicopterus',
    scientificName: 'Phoenicopterus',
    name: 'Phoenicopterus',
    rank: 'genus',
    parentId: 'taxon-phoenicopteridae',
    parentTaxonId: 'taxon-phoenicopteridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Flamingos',
    commonNameBn: 'ফ্ল্যামিঙ্গো গণ',
    description: 'Classic textbook avian representative of extreme trophic specialization and lamellar filtration.',
    isVerified: true
  },

  // --- MAMMALIA ---
  {
    id: 'taxon-hominidae',
    scientificName: 'Hominidae',
    name: 'Hominidae',
    rank: 'family',
    parentId: 'taxon-primates',
    parentTaxonId: 'taxon-primates',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1825',
    commonNameEn: 'Great apes and humans',
    commonNameBn: 'নরবানর ও মানব পরিবার',
    description: 'Large tailless catarrhine primates with high cranial capacity, complex social cognition, and dexterous hands.',
    isVerified: true
  },
  {
    id: 'taxon-homo',
    scientificName: 'Homo',
    name: 'Homo',
    rank: 'genus',
    parentId: 'taxon-hominidae',
    parentTaxonId: 'taxon-hominidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Humans',
    commonNameBn: 'মানুষ গণ',
    description: 'Obligate bipedal hominins characterized by expanded encephalization quotient, symbolic language, and cumulative culture.',
    isVerified: true
  },
  {
    id: 'taxon-felis',
    scientificName: 'Felis',
    name: 'Felis',
    rank: 'genus',
    parentId: 'taxon-felidae',
    parentTaxonId: 'taxon-felidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Small cats',
    commonNameBn: 'বিড়াল গণ',
    description: 'Carnivoran felids possessing non-roaring ossified hyoid apparatus, retractable claws, and vertical slit pupils.',
    isVerified: true
  },
  {
    id: 'taxon-perissodactyla',
    scientificName: 'Perissodactyla',
    name: 'Perissodactyla',
    rank: 'order',
    parentId: 'taxon-mammalia',
    parentTaxonId: 'taxon-mammalia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Owen, 1848',
    commonNameEn: 'Odd-toed ungulates',
    commonNameBn: 'বিজোড়-আঙ্গুলযুক্ত খুরওয়ালা প্রাণী বর্গ',
    description: 'Ungulate mammals in which the weight is borne predominantly on the third (central) digit (mesaxonic foot structure).',
    isVerified: true
  },
  {
    id: 'taxon-equidae',
    scientificName: 'Equidae',
    name: 'Equidae',
    rank: 'family',
    parentId: 'taxon-perissodactyla',
    parentTaxonId: 'taxon-perissodactyla',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1821',
    commonNameEn: 'Horses, zebras, and donkeys',
    commonNameBn: 'ঘোড়া পরিবার',
    description: 'Fast-running cursorial herbivores with single functional monodactyl hooves and hypsodont grinding dentition.',
    isVerified: true
  },
  {
    id: 'taxon-equus',
    scientificName: 'Equus',
    name: 'Equus',
    rank: 'genus',
    parentId: 'taxon-equidae',
    parentTaxonId: 'taxon-equidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Horses',
    commonNameBn: 'ঘোড়া গণ',
    description: 'Classic textbook evolutionary sequence demonstrating transitional morphological adaptations from forest browser to grassland runner.',
    isVerified: true
  },
  {
    id: 'taxon-proboscidea',
    scientificName: 'Proboscidea',
    name: 'Proboscidea',
    rank: 'order',
    parentId: 'taxon-mammalia',
    parentTaxonId: 'taxon-mammalia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Illiger, 1811',
    commonNameEn: 'Elephants',
    commonNameBn: 'হাতি বর্গ',
    description: 'Afrotherian megaherbivores characterized by a muscular prehensile proboscis (trunk) and modified incisor tusks.',
    isVerified: true
  },
  {
    id: 'taxon-elephantidae',
    scientificName: 'Elephantidae',
    name: 'Elephantidae',
    rank: 'family',
    parentId: 'taxon-proboscidea',
    parentTaxonId: 'taxon-proboscidea',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1821',
    commonNameEn: 'True elephants',
    commonNameBn: 'হাতি পরিবার',
    description: 'The largest living terrestrial mammals with graviportal columnar limbs and horizontal molar replacement.',
    isVerified: true
  },
  {
    id: 'taxon-elephas',
    scientificName: 'Elephas',
    name: 'Elephas',
    rank: 'genus',
    parentId: 'taxon-elephantidae',
    parentTaxonId: 'taxon-elephantidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Asian elephants',
    commonNameBn: 'এশীয় হাতি গণ',
    description: 'Critically important educational and cultural keystone species indigenous to South Asian forests, including Bangladesh.',
    isVerified: true
  },
  {
    id: 'taxon-muridae',
    scientificName: 'Muridae',
    name: 'Muridae',
    rank: 'family',
    parentId: 'taxon-rodentia',
    parentTaxonId: 'taxon-rodentia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Illiger, 1811',
    commonNameEn: 'True mice and rats',
    commonNameBn: 'ইঁদুর পরিবার',
    description: 'The largest mammalian family comprising gnawing rodents with continuously growing chisel-like incisors.',
    isVerified: true
  },
  {
    id: 'taxon-mus',
    scientificName: 'Mus',
    name: 'Mus',
    rank: 'genus',
    parentId: 'taxon-muridae',
    parentTaxonId: 'taxon-muridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Mice',
    commonNameBn: 'ইঁদুর গণ',
    description: 'The premier mammalian genetic, physiological, and biomedical laboratory model organism on Earth.',
    isVerified: true
  },
  {
    id: 'taxon-phascolarctidae',
    scientificName: 'Phascolarctidae',
    name: 'Phascolarctidae',
    rank: 'family',
    parentId: 'taxon-diprotodontia',
    parentTaxonId: 'taxon-diprotodontia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Owen, 1839',
    commonNameEn: 'Koalas',
    commonNameBn: 'কোয়ালা পরিবার',
    description: 'Arboreal herbivorous marsupials with syndactylous feet, backward-opening pouch, and vestigial tail.',
    isVerified: true
  },
  {
    id: 'taxon-phascolarctos',
    scientificName: 'Phascolarctos',
    name: 'Phascolarctos',
    rank: 'genus',
    parentId: 'taxon-phascolarctidae',
    parentTaxonId: 'taxon-phascolarctidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'de Blainville, 1816',
    commonNameEn: 'Koalas',
    commonNameBn: 'কোয়ালা গণ',
    description: 'World-famous marsupial specialized obligate folivore on Eucalyptus foliage.',
    isVerified: true
  }
];

module.exports = {
  TEXTBOOK_TAXA_NODES
};
