// scripts/build_master_fix_14_data.cjs
// Curates and compiles deep taxonomic nodes (Families, Genera) and canonical species records for MASTER-FIX-14
const fs = require('fs');
const path = require('path');

const SEED_TAXA_PATH = path.resolve(__dirname, '../src/data/seedTaxa.ts');
const SEED_SPECIES_PATH = path.resolve(__dirname, '../src/data/seedSpecies.ts');
const SEED_REFS_PATH = path.resolve(__dirname, '../src/data/seedReferences.ts');

// ─────────────────────────────────────────────────────────────────────────────
// 1. NEW TAXONOMIC NODES (Orders, Families, Genera)
// ─────────────────────────────────────────────────────────────────────────────
const NEW_TAXA_NODES = [
  // --- PORIFERA ---
  {
    id: 'taxon-sycettidae',
    scientificName: 'Sycettidae',
    name: 'Sycettidae',
    rank: 'family',
    parentId: 'taxon-leucosoleniida',
    parentTaxonId: 'taxon-leucosoleniida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Dendy, 1892',
    commonNameEn: 'Syconoid calcareous sponges',
    commonNameBn: 'সাইকোনয়েড চুনযুক্ত স্পঞ্জ পরিবার',
    description: 'Calcareous sponges with syconoid architecture and articulated spicular radial tubes.',
    isVerified: true
  },
  {
    id: 'taxon-sycon',
    scientificName: 'Sycon',
    name: 'Sycon',
    rank: 'genus',
    parentId: 'taxon-sycettidae',
    parentTaxonId: 'taxon-sycettidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Risso, 1826',
    commonNameEn: 'Purse sponges',
    commonNameBn: 'পার্স স্পঞ্জ গণ',
    description: 'Marine calcareous sponges possessing distinct radial chambers lined with choanocytes.',
    isVerified: true
  },
  {
    id: 'taxon-suberitida',
    scientificName: 'Suberitida',
    name: 'Suberitida',
    rank: 'order',
    parentId: 'taxon-demospongiae',
    parentTaxonId: 'taxon-demospongiae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Chombard & Boury-Esnault, 1999',
    commonNameEn: 'Suberitid demosponges',
    commonNameBn: 'সুবেইরিটা পর্বভুক্ত ডেমোস্পঞ্জ',
    description: 'Demosponges characterized by tylostyle megascleres arranged in dense radiating surface bouquets.',
    isVerified: true
  },
  {
    id: 'taxon-suberitidae',
    scientificName: 'Suberitidae',
    name: 'Suberitidae',
    rank: 'family',
    parentId: 'taxon-suberitida',
    parentTaxonId: 'taxon-suberitida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Schmidt, 1870',
    commonNameEn: 'Sea orange sponges',
    commonNameBn: 'সি অরেঞ্জ স্পঞ্জ পরিবার',
    description: 'Compact demosponges often living symbiotically on gastropod shells inhabited by hermit crabs.',
    isVerified: true
  },
  {
    id: 'taxon-suberites',
    scientificName: 'Suberites',
    name: 'Suberites',
    rank: 'genus',
    parentId: 'taxon-suberitidae',
    parentTaxonId: 'taxon-suberitidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Nardo, 1833',
    commonNameEn: 'Suberites sponges',
    commonNameBn: 'সুবেইরাইটিস স্পঞ্জ গণ',
    description: 'Dome-shaped demosponges with smooth velvet-like surface and intense pigmentation.',
    isVerified: true
  },
  {
    id: 'taxon-amphidiscosida',
    scientificName: 'Amphidiscosida',
    name: 'Amphidiscosida',
    rank: 'order',
    parentId: 'taxon-hexactinellida',
    parentTaxonId: 'taxon-hexactinellida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Schrammen, 1924',
    commonNameEn: 'Amphidisc glass sponges',
    commonNameBn: 'এমফিডিস্ক কাচ স্পঞ্জ',
    description: 'Hexactinellid sponges with amphidisc microscleres and continuous anchoring spicular tufts.',
    isVerified: true
  },
  {
    id: 'taxon-hyalonematidae',
    scientificName: 'Hyalonematidae',
    name: 'Hyalonematidae',
    rank: 'family',
    parentId: 'taxon-amphidiscosida',
    parentTaxonId: 'taxon-amphidiscosida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1857',
    commonNameEn: 'Glass rope sponges',
    commonNameBn: 'কাচ দড়ি স্পঞ্জ পরিবার',
    description: 'Deep-sea hexactinellids elevated on a twisted anchoring stalk of long glass spicules.',
    isVerified: true
  },
  {
    id: 'taxon-hyalonema',
    scientificName: 'Hyalonema',
    name: 'Hyalonema',
    rank: 'genus',
    parentId: 'taxon-hyalonematidae',
    parentTaxonId: 'taxon-hyalonematidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1832',
    commonNameEn: 'Glass rope sponge genus',
    commonNameBn: 'হায়ালোনেমা কাচ স্পঞ্জ গণ',
    description: 'Goblet or mushroom-shaped sponge supported by a long braided stalk of siliceous spicules anchoring in deep mud.',
    isVerified: true
  },

  // --- CNIDARIA ---
  {
    id: 'taxon-actiniaria',
    scientificName: 'Actiniaria',
    name: 'Actiniaria',
    rank: 'order',
    parentId: 'taxon-anthozoa',
    parentTaxonId: 'taxon-anthozoa',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Hertwig, 1882',
    commonNameEn: 'Sea anemones',
    commonNameBn: 'সি অ্যানিমোন বর্গ',
    description: 'Solitary, predatory hexacorallians lacking mineralized skeletons, anchored by pedal disc.',
    isVerified: true
  },
  {
    id: 'taxon-actiniidae',
    scientificName: 'Actiniidae',
    name: 'Actiniidae',
    rank: 'family',
    parentId: 'taxon-actiniaria',
    parentTaxonId: 'taxon-actiniaria',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'True sea anemones',
    commonNameBn: 'প্রকৃত সি অ্যানিমোন পরিবার',
    description: 'The largest family of sea anemones with smooth or verrucose column and numerous simple tentacles.',
    isVerified: true
  },
  {
    id: 'taxon-actinia',
    scientificName: 'Actinia',
    name: 'Actinia',
    rank: 'genus',
    parentId: 'taxon-actiniidae',
    parentTaxonId: 'taxon-actiniidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1767',
    commonNameEn: 'Beadlet anemones',
    commonNameBn: 'বিডলেট অ্যানিমোন গণ',
    description: 'Intertidal anemones with a ring of marginal spherules packed with specialized cnidocytes.',
    isVerified: true
  },
  {
    id: 'taxon-semaeostomeae',
    scientificName: 'Semaeostomeae',
    name: 'Semaeostomeae',
    rank: 'order',
    parentId: 'taxon-scyphozoa',
    parentTaxonId: 'taxon-scyphozoa',
    status: 'accepted',
    module: 'marine',
    authorYear: 'L. Agassiz, 1862',
    commonNameEn: 'Flag-mouth jellyfish',
    commonNameBn: 'পতাকামুখী জেলিফিশ বর্গ',
    description: 'True scyphozoan jellyfish with umbrella-shaped bells, scalloped margins, and four long ruffled oral arms.',
    isVerified: true
  },
  {
    id: 'taxon-pelagiidae',
    scientificName: 'Pelagiidae',
    name: 'Pelagiidae',
    rank: 'family',
    parentId: 'taxon-semaeostomeae',
    parentTaxonId: 'taxon-semaeostomeae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gegenbaur, 1856',
    commonNameEn: 'Pelagic jellyfish',
    commonNameBn: 'মুক্তসাঁতারু জেলিফিশ পরিবার',
    description: 'Open-ocean scyphomedusae with 8 or 16 marginal tentacles and stinging nematocysts.',
    isVerified: true
  },
  {
    id: 'taxon-chrysaora',
    scientificName: 'Chrysaora',
    name: 'Chrysaora',
    rank: 'genus',
    parentId: 'taxon-pelagiidae',
    parentTaxonId: 'taxon-pelagiidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Péron & Lesueur, 1810',
    commonNameEn: 'Sea nettles',
    commonNameBn: 'সি নেটেল জেলিফিশ গণ',
    description: 'Prominent marine medusae with distinct radial banding patterns on bell and long stinging tentacles.',
    isVerified: true
  },
  {
    id: 'taxon-leptothecata',
    scientificName: 'Leptothecata',
    name: 'Leptothecata',
    rank: 'order',
    parentId: 'taxon-hydrozoa',
    parentTaxonId: 'taxon-hydrozoa',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Cornelius, 1992',
    commonNameEn: 'Thecate hydroids',
    commonNameBn: 'আবরণযুক্ত হাইড্রয়েড বর্গ',
    description: 'Hydrozoans whose polyps are encased in a chitinous protective cup known as a hydrotheca.',
    isVerified: true
  },
  {
    id: 'taxon-campanulariidae',
    scientificName: 'Campanulariidae',
    name: 'Campanulariidae',
    rank: 'family',
    parentId: 'taxon-leptothecata',
    parentTaxonId: 'taxon-leptothecata',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Johnston, 1837',
    commonNameEn: 'Bell hydroids',
    commonNameBn: 'ঘণ্টা হাইড্রয়েড পরিবার',
    description: 'Colonial hydroids with wine-glass or bell-shaped hydrothecae on branched stalks.',
    isVerified: true
  },
  {
    id: 'taxon-obelia',
    scientificName: 'Obelia',
    name: 'Obelia',
    rank: 'genus',
    parentId: 'taxon-campanulariidae',
    parentTaxonId: 'taxon-campanulariidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Péron & Lesueur, 1810',
    commonNameEn: 'Sea furs',
    commonNameBn: 'সি ফার / ওবেলিয়া গণ',
    description: 'Classic textbook hydrozoan displaying distinct metagenesis between sessile branching hydroid colony and tiny free-swimming medusae.',
    isVerified: true
  },

  // --- CTENOPHORA ---
  {
    id: 'taxon-lobata',
    scientificName: 'Lobata',
    name: 'Lobata',
    rank: 'order',
    parentId: 'taxon-tentaculata',
    parentTaxonId: 'taxon-tentaculata',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Eschscholtz, 1829',
    commonNameEn: 'Lobed comb jellies',
    commonNameBn: 'খণ্ডিত কম্ব জেলি বর্গ',
    description: 'Tentaculate ctenophores possessing a pair of prominent muscular feeding oral lobes and four auricles.',
    isVerified: true
  },
  {
    id: 'taxon-bolinopsidae',
    scientificName: 'Bolinopsidae',
    name: 'Bolinopsidae',
    rank: 'family',
    parentId: 'taxon-lobata',
    parentTaxonId: 'taxon-lobata',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Bigelow, 1912',
    commonNameEn: 'Sea walnut family',
    commonNameBn: 'সি ওয়ালনাট কম্ব জেলি পরিবার',
    description: 'Transparent lobate ctenophores with short tentacle sheaths and ciliated oral lobes.',
    isVerified: true
  },
  {
    id: 'taxon-mnemiopsis',
    scientificName: 'Mnemiopsis',
    name: 'Mnemiopsis',
    rank: 'genus',
    parentId: 'taxon-bolinopsidae',
    parentTaxonId: 'taxon-bolinopsidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'L. Agassiz, 1860',
    commonNameEn: 'Warty comb jellies',
    commonNameBn: 'নেমিওপসিস কম্ব জেলি গণ',
    description: 'Carnivorous pelagic ctenophores famous for intense bioluminescence and invasive potential in semi-enclosed seas.',
    isVerified: true
  },

  // --- ANNELIDA ---
  {
    id: 'taxon-phyllodocida',
    scientificName: 'Phyllodocida',
    name: 'Phyllodocida',
    rank: 'order',
    parentId: 'taxon-polychaeta',
    parentTaxonId: 'taxon-polychaeta',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Dales, 1962',
    commonNameEn: 'Paddle worms and ragworms',
    commonNameBn: 'প্যাডেল কীট ও র্যাগওয়ার্ম বর্গ',
    description: 'Errant polychaete worms with well-developed prostomial sensory appendages, muscular eversible pharynx, and chaeta-bearing parapodia.',
    isVerified: true
  },
  {
    id: 'taxon-nereididae',
    scientificName: 'Nereididae',
    name: 'Nereididae',
    rank: 'family',
    parentId: 'taxon-phyllodocida',
    parentTaxonId: 'taxon-phyllodocida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Blainville, 1818',
    commonNameEn: 'Ragworms / Clam worms',
    commonNameBn: 'র্যাগওয়ার্ম পরিবার',
    description: 'Predatory and scavenger marine worms with four pairs of peristomial tentacular cirri and jaw-bearing proboscis.',
    isVerified: true
  },
  {
    id: 'taxon-alitta',
    scientificName: 'Alitta',
    name: 'Alitta',
    rank: 'genus',
    parentId: 'taxon-nereididae',
    parentTaxonId: 'taxon-nereididae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Kinberg, 1865',
    commonNameEn: 'King ragworms',
    commonNameBn: 'কিং র্যাগওয়ার্ম গণ',
    description: 'Large coastal nereidid polychaetes extensively utilized as marine live bait and benthic ecological indicators.',
    isVerified: true
  },
  {
    id: 'taxon-haplotaxida',
    scientificName: 'Haplotaxida',
    name: 'Haplotaxida',
    rank: 'order',
    parentId: 'taxon-clitellata',
    parentTaxonId: 'taxon-clitellata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Brinkhurst, 1971',
    commonNameEn: 'Aquatic and terrestrial oligochaetes',
    commonNameBn: 'অলিগোকিট বর্গ',
    description: 'Clitellate annelids with simple segmented chaetae and hermaphroditic reproductive systems producing cocoons.',
    isVerified: true
  },
  {
    id: 'taxon-naididae',
    scientificName: 'Naididae',
    name: 'Naididae',
    rank: 'family',
    parentId: 'taxon-haplotaxida',
    parentTaxonId: 'taxon-haplotaxida',
    status: 'accepted',
    module: 'general',
    authorYear: 'Ehrenberg, 1828',
    commonNameEn: 'Sludge worms and aquatic oligochaetes',
    commonNameBn: 'স্লাজ ওয়ার্ম পরিবার',
    description: 'Benthic freshwater oligochaetes capable of surviving in extreme hypoxia through erythrocruorin hemoglobin pigments.',
    isVerified: true
  },
  {
    id: 'taxon-tubifex',
    scientificName: 'Tubifex',
    name: 'Tubifex',
    rank: 'genus',
    parentId: 'taxon-naididae',
    parentTaxonId: 'taxon-naididae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Lamarck, 1816',
    commonNameEn: 'Tubifex worms',
    commonNameBn: 'টিউবিফেক্স কেঁচো গণ',
    description: 'Colonial sludge worms anchoring heads in organic sediment while undulating red tails for respiratory gas exchange.',
    isVerified: true
  },

  // --- MOLLUSCA ---
  {
    id: 'taxon-neogastropoda',
    scientificName: 'Neogastropoda',
    name: 'Neogastropoda',
    rank: 'order',
    parentId: 'taxon-gastropoda',
    parentTaxonId: 'taxon-gastropoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Wenz, 1938',
    commonNameEn: 'Carnivorous marine snails',
    commonNameBn: 'মাংসাশী সামুদ্রিক শামুক বর্গ',
    description: 'Advanced marine gastropods with a siphonal canal, radula adapted for predation, and single bipectinate ctenidium.',
    isVerified: true
  },
  {
    id: 'taxon-conidae',
    scientificName: 'Conidae',
    name: 'Conidae',
    rank: 'family',
    parentId: 'taxon-neogastropoda',
    parentTaxonId: 'taxon-neogastropoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Fleming, 1822',
    commonNameEn: 'Cone snails',
    commonNameBn: 'কোন শামুক পরিবার',
    description: 'Predatory marine snails armed with harpoon-like hollow radular teeth injecting complex conotoxin venom cocktails.',
    isVerified: true
  },
  {
    id: 'taxon-conus',
    scientificName: 'Conus',
    name: 'Conus',
    rank: 'genus',
    parentId: 'taxon-conidae',
    parentTaxonId: 'taxon-conidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'True cone snails',
    commonNameBn: 'কোন শামুক গণ',
    description: 'Invert- and fish-hunting marine snails with heavy conical shells and lethal neurotoxic stings.',
    isVerified: true
  },
  {
    id: 'taxon-mytilida',
    scientificName: 'Mytilida',
    name: 'Mytilida',
    rank: 'order',
    parentId: 'taxon-bivalvia',
    parentTaxonId: 'taxon-bivalvia',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Férussac, 1822',
    commonNameEn: 'True marine mussels',
    commonNameBn: 'সামুদ্রিক ঝিনুক বর্গ',
    description: 'Bivalves attached to hard substrate via proteinaceous byssal threads, with heteromyarian adductor muscle structure.',
    isVerified: true
  },
  {
    id: 'taxon-mytilidae',
    scientificName: 'Mytilidae',
    name: 'Mytilidae',
    rank: 'family',
    parentId: 'taxon-mytilida',
    parentTaxonId: 'taxon-mytilida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'Mussel family',
    commonNameBn: 'মাইটিলিড ঝিনুক পরিবার',
    description: 'Epifaunal filter-feeding bivalves with wedge-shaped shells and strong byssus anchoring systems.',
    isVerified: true
  },
  {
    id: 'taxon-mytilus',
    scientificName: 'Mytilus',
    name: 'Mytilus',
    rank: 'genus',
    parentId: 'taxon-mytilidae',
    parentTaxonId: 'taxon-mytilidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Blue mussels',
    commonNameBn: 'ব্লু মাসেল গণ',
    description: 'Commercially vital intertidal blue and black mussels forming extensive biogenic mussel beds on temperate coasts.',
    isVerified: true
  },
  {
    id: 'taxon-ostreida',
    scientificName: 'Ostreida',
    name: 'Ostreida',
    rank: 'order',
    parentId: 'taxon-bivalvia',
    parentTaxonId: 'taxon-bivalvia',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Férussac, 1822',
    commonNameEn: 'True oysters',
    commonNameBn: 'প্রকৃত ঝিনুক বর্গ',
    description: 'Monomarian marine bivalves cementing their left valve permanently onto hard substrate.',
    isVerified: true
  },
  {
    id: 'taxon-ostreidae',
    scientificName: 'Ostreidae',
    name: 'Ostreidae',
    rank: 'family',
    parentId: 'taxon-ostreida',
    parentTaxonId: 'taxon-ostreida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'Oyster family',
    commonNameBn: 'অয়েস্টার পরিবার',
    description: 'Irregular-shelled bivalves forming massive biogenic reef systems in estuaries and coastal lagoons.',
    isVerified: true
  },
  {
    id: 'taxon-crassostrea',
    scientificName: 'Crassostrea',
    name: 'Crassostrea',
    rank: 'genus',
    parentId: 'taxon-ostreidae',
    parentTaxonId: 'taxon-ostreidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Sacco, 1897',
    commonNameEn: 'Cupped oysters',
    commonNameBn: 'কাপড অয়েস্টার গণ',
    description: 'Deep-cupped oysters representing the most widely cultivated marine bivalves in global aquaculture.',
    isVerified: true
  },
  {
    id: 'taxon-octopoda',
    scientificName: 'Octopoda',
    name: 'Octopoda',
    rank: 'order',
    parentId: 'taxon-cephalopoda',
    parentTaxonId: 'taxon-cephalopoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Leach, 1818',
    commonNameEn: 'Octopuses',
    commonNameBn: 'অক্টোপাস বর্গ',
    description: 'Eight-armed coleoid cephalopods with highly encephalized nervous systems, bilateral symmetry, and no internal shell.',
    isVerified: true
  },
  {
    id: 'taxon-octopodidae',
    scientificName: 'Octopodidae',
    name: 'Octopodidae',
    rank: 'family',
    parentId: 'taxon-octopoda',
    parentTaxonId: 'taxon-octopoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'd’Orbigny, 1840',
    commonNameEn: 'Benthic octopuses',
    commonNameBn: 'তলদেশবাসী অক্টোপাস পরিবার',
    description: 'Benthic eight-limbed cephalopods with biserial sucker arrangement and ink sacs.',
    isVerified: true
  },
  {
    id: 'taxon-octopus',
    scientificName: 'Octopus',
    name: 'Octopus',
    rank: 'genus',
    parentId: 'taxon-octopodidae',
    parentTaxonId: 'taxon-octopodidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Cuvier, 1797',
    commonNameEn: 'Common octopuses',
    commonNameBn: 'সাধারণ অক্টোপাস গণ',
    description: 'Intelligent benthic predators capable of rapid dynamic camouflage, tool use, and complex problem-solving.',
    isVerified: true
  },

  // --- ARTHROPODA ---
  {
    id: 'taxon-portunidae',
    scientificName: 'Portunidae',
    name: 'Portunidae',
    rank: 'family',
    parentId: 'taxon-decapoda',
    parentTaxonId: 'taxon-decapoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'Swimming crabs',
    commonNameBn: 'সাঁতারু কাঁকড়া পরিবার',
    description: 'Decapod crabs whose fifth pair of pereiopods is flattened into paddle-shaped swimming dactyls.',
    isVerified: true
  },
  {
    id: 'taxon-callinectes',
    scientificName: 'Callinectes',
    name: 'Callinectes',
    rank: 'genus',
    parentId: 'taxon-portunidae',
    parentTaxonId: 'taxon-portunidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Stimpson, 1860',
    commonNameEn: 'Blue crabs',
    commonNameBn: 'নীল কাঁকড়া গণ',
    description: 'Fast-swimming coastal and estuarine crabs with strong chelipeds and broad lateral spine on carapace.',
    isVerified: true
  },
  {
    id: 'taxon-palinuridae',
    scientificName: 'Palinuridae',
    name: 'Palinuridae',
    rank: 'family',
    parentId: 'taxon-decapoda',
    parentTaxonId: 'taxon-decapoda',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Latreille, 1802',
    commonNameEn: 'Spiny lobsters',
    commonNameBn: 'স্পাইনি লবস্টার পরিবার',
    description: 'Decapods lacking large claws, equipped with long spiny antennae and phyllosoma planktonic larvae.',
    isVerified: true
  },
  {
    id: 'taxon-panulirus',
    scientificName: 'Panulirus',
    name: 'Panulirus',
    rank: 'genus',
    parentId: 'taxon-palinuridae',
    parentTaxonId: 'taxon-palinuridae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'White, 1847',
    commonNameEn: 'Tropical spiny lobsters',
    commonNameBn: 'ক্রান্তীয় কাঁটা লবস্টার গণ',
    description: 'Nocturnal reef-dwelling decapod crustaceans characterized by cylindrical cephalothorax and long antennular flagella.',
    isVerified: true
  },
  {
    id: 'taxon-arachnida',
    scientificName: 'Arachnida',
    name: 'Arachnida',
    rank: 'class',
    parentId: 'taxon-arthropoda',
    parentTaxonId: 'taxon-arthropoda',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cuvier, 1812',
    commonNameEn: 'Arachnids',
    commonNameBn: 'অ্যারাকনিডা / মাকড়সা-জাতীয় শ্রেণি',
    description: 'Eight-legged terrestrial chelicerate arthropods with body divided into prosoma and opisthosoma.',
    isVerified: true
  },
  {
    id: 'taxon-araneae',
    scientificName: 'Araneae',
    name: 'Araneae',
    rank: 'order',
    parentId: 'taxon-arachnida',
    parentTaxonId: 'taxon-arachnida',
    status: 'accepted',
    module: 'general',
    authorYear: 'Clerck, 1757',
    commonNameEn: 'Spiders',
    commonNameBn: 'মাকড়সা বর্গ',
    description: 'Chelicerates with eight legs, chelicerae modified into venom-injecting fangs, and abdominal spinnerets spinning silk.',
    isVerified: true
  },
  {
    id: 'taxon-theridiidae',
    scientificName: 'Theridiidae',
    name: 'Theridiidae',
    rank: 'family',
    parentId: 'taxon-araneae',
    parentTaxonId: 'taxon-araneae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Sundevall, 1833',
    commonNameEn: 'Cobweb spiders / Comb-footed spiders',
    commonNameBn: 'জালবোনা মাকড়সা পরিবার',
    description: 'Araneomorph spiders constructing irregular tangled webs and possessing serrated setae on fourth tarsi.',
    isVerified: true
  },
  {
    id: 'taxon-latrodectus',
    scientificName: 'Latrodectus',
    name: 'Latrodectus',
    rank: 'genus',
    parentId: 'taxon-theridiidae',
    parentTaxonId: 'taxon-theridiidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Walckenaer, 1805',
    commonNameEn: 'Widow spiders',
    commonNameBn: 'উইডো মাকড়সা গণ',
    description: 'Venomous cobweb spiders producing potent alpha-latrotoxin causing severe systemic latrodectism.',
    isVerified: true
  },
  {
    id: 'taxon-diptera',
    scientificName: 'Diptera',
    name: 'Diptera',
    rank: 'order',
    parentId: 'taxon-insecta',
    parentTaxonId: 'taxon-insecta',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'True flies and mosquitoes',
    commonNameBn: 'মাছি ও মশা বর্গ',
    description: 'Insects possessing only a single pair of functional flight wings; hindwings reduced to gyroscopic halteres.',
    isVerified: true
  },
  {
    id: 'taxon-culicidae',
    scientificName: 'Culicidae',
    name: 'Culicidae',
    rank: 'family',
    parentId: 'taxon-diptera',
    parentTaxonId: 'taxon-diptera',
    status: 'accepted',
    module: 'general',
    authorYear: 'Meigen, 1818',
    commonNameEn: 'Mosquitoes',
    commonNameBn: 'মশা পরিবার',
    description: 'Slender nematoceran flies with piercing-sucking proboscis in females and aquatic larval development.',
    isVerified: true
  },
  {
    id: 'taxon-aedes',
    scientificName: 'Aedes',
    name: 'Aedes',
    rank: 'genus',
    parentId: 'taxon-culicidae',
    parentTaxonId: 'taxon-culicidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Meigen, 1818',
    commonNameEn: 'Aedes mosquitoes',
    commonNameBn: 'এডিস মশা গণ',
    description: 'Day-biting striped mosquitoes serving as primary vectors for dengue, yellow fever, chikungunya, and Zika virus.',
    isVerified: true
  },
  {
    id: 'taxon-coleoptera',
    scientificName: 'Coleoptera',
    name: 'Coleoptera',
    rank: 'order',
    parentId: 'taxon-insecta',
    parentTaxonId: 'taxon-insecta',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Beetles',
    commonNameBn: 'গুবরে পোকা / বিটল বর্গ',
    description: 'The largest insect order, defined by hardened protective front wings (elytra) covering membranous flight wings.',
    isVerified: true
  },
  {
    id: 'taxon-scarabaeidae',
    scientificName: 'Scarabaeidae',
    name: 'Scarabaeidae',
    rank: 'family',
    parentId: 'taxon-coleoptera',
    parentTaxonId: 'taxon-coleoptera',
    status: 'accepted',
    module: 'general',
    authorYear: 'Latreille, 1802',
    commonNameEn: 'Scarab beetles',
    commonNameBn: 'স্কারাব বিটল পরিবার',
    description: 'Heavy-bodied beetles with distinctive lamellate antennae that fan out to sense pheromones and dung odors.',
    isVerified: true
  },
  {
    id: 'taxon-scarabaeus',
    scientificName: 'Scarabaeus',
    name: 'Scarabaeus',
    rank: 'genus',
    parentId: 'taxon-scarabaeidae',
    parentTaxonId: 'taxon-scarabaeidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Sacred scarab beetles',
    commonNameBn: 'পবিত্র স্কারাব বিটল গণ',
    description: 'Dung-rolling beetles exhibiting complex brood ball construction and celestial navigation.',
    isVerified: true
  },

  // --- ECHINODERMATA ---
  {
    id: 'taxon-valvatida',
    scientificName: 'Valvatida',
    name: 'Valvatida',
    rank: 'order',
    parentId: 'taxon-asteroidea',
    parentTaxonId: 'taxon-asteroidea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Perrier, 1884',
    commonNameEn: 'Valvatid sea stars',
    commonNameBn: 'ভালভাটিডা তারা মাছ বর্গ',
    description: 'Sea stars characterized by conspicuous marginal ossicles and valve-like pedicellariae.',
    isVerified: true
  },
  {
    id: 'taxon-oreasteridae',
    scientificName: 'Oreasteridae',
    name: 'Oreasteridae',
    rank: 'family',
    parentId: 'taxon-valvatida',
    parentTaxonId: 'taxon-valvatida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Fisher, 1911',
    commonNameEn: 'Cushion stars and knobby stars',
    commonNameBn: 'কুশন স্টার পরিবার',
    description: 'Massive tropical reef sea stars with heavy calcified tubercles or spines on aboral disc.',
    isVerified: true
  },
  {
    id: 'taxon-protoreaster',
    scientificName: 'Protoreaster',
    name: 'Protoreaster',
    rank: 'genus',
    parentId: 'taxon-oreasteridae',
    parentTaxonId: 'taxon-oreasteridae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Döderlein, 1916',
    commonNameEn: 'Horned sea stars',
    commonNameBn: 'শিংযুক্ত তারা মাছ গণ',
    description: 'Sturdy tropical Indo-Pacific sea stars with prominent black or dark red horn-like knobs.',
    isVerified: true
  },
  {
    id: 'taxon-camarodonta',
    scientificName: 'Camarodonta',
    name: 'Camarodonta',
    rank: 'order',
    parentId: 'taxon-echinoidea',
    parentTaxonId: 'taxon-echinoidea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Jackson, 1912',
    commonNameEn: 'Regular sea urchins',
    commonNameBn: 'নিয়মিত সি আর্চিন বর্গ',
    description: 'Regular echinoids with fused epiphyses on Aristotle’s lantern and keeled teeth.',
    isVerified: true
  },
  {
    id: 'taxon-strongylocentrotidae',
    scientificName: 'Strongylocentrotidae',
    name: 'Strongylocentrotidae',
    rank: 'family',
    parentId: 'taxon-camarodonta',
    parentTaxonId: 'taxon-camarodonta',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gregory, 1900',
    commonNameEn: 'Strongylocentrotid urchins',
    commonNameBn: 'স্ট্রংগিলোসেনট্রোটিড আর্চিন পরিবার',
    description: 'Cold-water sea urchins playing keystone grazing roles in temperate kelp forest ecosystems.',
    isVerified: true
  },
  {
    id: 'taxon-mesocentrotus',
    scientificName: 'Mesocentrotus',
    name: 'Mesocentrotus',
    rank: 'genus',
    parentId: 'taxon-strongylocentrotidae',
    parentTaxonId: 'taxon-strongylocentrotidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Tatarenko & Poltaraus, 1993',
    commonNameEn: 'Giant red sea urchins',
    commonNameBn: 'দৈত্যাকার লাল আর্চিন গণ',
    description: 'Large, long-lived Pacific sea urchins with sharp protective spines and immense commercial roe fishery value.',
    isVerified: true
  },
  {
    id: 'taxon-holothuriida',
    scientificName: 'Holothuriida',
    name: 'Holothuriida',
    rank: 'order',
    parentId: 'taxon-holothuroidea',
    parentTaxonId: 'taxon-holothuroidea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Miller et al., 2017',
    commonNameEn: 'True sea cucumbers',
    commonNameBn: 'প্রকৃত সমুদ্র শসা বর্গ',
    description: 'Aspidochirote sea cucumbers with peltate feeding tentacles and Cuvierian organ defensive tubules.',
    isVerified: true
  },
  {
    id: 'taxon-holothuriidae',
    scientificName: 'Holothuriidae',
    name: 'Holothuriidae',
    rank: 'family',
    parentId: 'taxon-holothuriida',
    parentTaxonId: 'taxon-holothuriida',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Burmeister, 1837',
    commonNameEn: 'Holothuriid sea cucumbers',
    commonNameBn: 'হলোথুরিয়া পরিবার',
    description: 'Thick-walled benthic deposit feeders forming the foundation of tropical bêche-de-mer fisheries.',
    isVerified: true
  },
  {
    id: 'taxon-holothuria',
    scientificName: 'Holothuria',
    name: 'Holothuria',
    rank: 'genus',
    parentId: 'taxon-holothuriidae',
    parentTaxonId: 'taxon-holothuriidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Linnaeus, 1767',
    commonNameEn: 'Holothuria sea cucumbers',
    commonNameBn: 'হলোথুরিয়া গণ',
    description: 'Diverse tropical deposit-feeding sea cucumbers vital for nutrient recycling and sediment bioturbation on coral reefs.',
    isVerified: true
  },

  // --- FISHES (DEEPENING FAMILIES & GENERA UNDER 73 ORDERS) ---
  {
    id: 'taxon-lamnidae',
    scientificName: 'Lamnidae',
    name: 'Lamnidae',
    rank: 'family',
    parentId: 'taxon-lamniformes',
    parentTaxonId: 'taxon-lamniformes',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Müller & Henle, 1838',
    commonNameEn: 'Mackerel sharks / White sharks',
    commonNameBn: 'ম্যাকেরেল হাঙর পরিবার',
    description: 'Fast-swimming endothermic sharks with conical snouts, heavy spindles, and lunate caudal fins.',
    isVerified: true
  },
  {
    id: 'taxon-carcharodon',
    scientificName: 'Carcharodon',
    name: 'Carcharodon',
    rank: 'genus',
    parentId: 'taxon-lamnidae',
    parentTaxonId: 'taxon-lamnidae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Smith, 1838',
    commonNameEn: 'White shark genus',
    commonNameBn: 'সাদা হাঙর গণ',
    description: 'Apex marine predator armed with large triangular serrated teeth and regional endothermy.',
    isVerified: true
  },
  {
    id: 'taxon-rhincodontidae',
    scientificName: 'Rhincodontidae',
    name: 'Rhincodontidae',
    rank: 'family',
    parentId: 'taxon-orectolobiformes',
    parentTaxonId: 'taxon-orectolobiformes',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Müller & Henle, 1839',
    commonNameEn: 'Whale sharks',
    commonNameBn: 'তিমি হাঙর পরিবার',
    description: 'Monotypic family of giant filter-feeding carpet sharks cruising tropical pelagic oceans.',
    isVerified: true
  },
  {
    id: 'taxon-rhincodon',
    scientificName: 'Rhincodon',
    name: 'Rhincodon',
    rank: 'genus',
    parentId: 'taxon-rhincodontidae',
    parentTaxonId: 'taxon-rhincodontidae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Smith, 1828',
    commonNameEn: 'Whale shark genus',
    commonNameBn: 'তিমি হাঙর গণ',
    description: 'The largest extant non-mammalian vertebrate, possessing a broad flattened head and filter-feeding gill apparatus.',
    isVerified: true
  },
  {
    id: 'taxon-protopteridae',
    scientificName: 'Protopteridae',
    name: 'Protopteridae',
    rank: 'family',
    parentId: 'taxon-ceratodontiformes',
    parentTaxonId: 'taxon-ceratodontiformes',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Peters, 1855',
    commonNameEn: 'African lungfishes',
    commonNameBn: 'আফ্রিকান ফুসফুস মাছ পরিবার',
    description: 'Obligate air-breathing sarcopterygian dipnoans capable of estivating in subterranean mud cocoons for years.',
    isVerified: true
  },
  {
    id: 'taxon-protopterus',
    scientificName: 'Protopterus',
    name: 'Protopterus',
    rank: 'genus',
    parentId: 'taxon-protopteridae',
    parentTaxonId: 'taxon-protopteridae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Owen, 1839',
    commonNameEn: 'African lungfish genus',
    commonNameBn: 'প্রোটোপটেরাস ফুসফুস মাছ গণ',
    description: 'Elongated lobe-finned freshwater fishes with filament-like pectoral and pelvic fins and paired functional lungs.',
    isVerified: true
  },
  {
    id: 'taxon-phycodurus',
    scientificName: 'Phycodurus',
    name: 'Phycodurus',
    rank: 'genus',
    parentId: 'taxon-syngnathidae',
    parentTaxonId: 'taxon-syngnathidae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Gill, 1896',
    commonNameEn: 'Leafy seadragons',
    commonNameBn: 'পাতাসদৃশ সিড্রাগন গণ',
    description: 'Masterfully camouflaged syngnathid with leaf-like appendages providing mimicry among kelp and macroalgae.',
    isVerified: true
  },
  {
    id: 'taxon-diodontidae',
    scientificName: 'Diodontidae',
    name: 'Diodontidae',
    rank: 'family',
    parentId: 'taxon-tetraodontiformes',
    parentTaxonId: 'taxon-tetraodontiformes',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Bilberg, 1820',
    commonNameEn: 'Porcupinefishes / Burrfish',
    commonNameBn: 'সজারু মাছ পরিবার',
    description: 'Tetraodontiform fishes covered in sharp, erectile spines that inflate when threatened.',
    isVerified: true
  },
  {
    id: 'taxon-diodon',
    scientificName: 'Diodon',
    name: 'Diodon',
    rank: 'genus',
    parentId: 'taxon-diodontidae',
    parentTaxonId: 'taxon-diodontidae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Porcupinefishes',
    commonNameBn: 'সজারু মাছ গণ',
    description: 'Reef and coastal globose fishes with fused beak-like dental plates crushing hard-shelled molluscs and crabs.',
    isVerified: true
  },
  {
    id: 'taxon-muraenidae',
    scientificName: 'Muraenidae',
    name: 'Muraenidae',
    rank: 'family',
    parentId: 'taxon-anguilliformes',
    parentTaxonId: 'taxon-anguilliformes',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'Moray eels',
    commonNameBn: 'মোরে ঈল পরিবার',
    description: 'Scaleless predatory eels possessing powerful pharyngeal jaws for grasping and swallowing prey.',
    isVerified: true
  },
  {
    id: 'taxon-gymnothorax',
    scientificName: 'Gymnothorax',
    name: 'Gymnothorax',
    rank: 'genus',
    parentId: 'taxon-muraenidae',
    parentTaxonId: 'taxon-muraenidae',
    status: 'accepted',
    module: 'fish',
    authorYear: 'Bloch, 1795',
    commonNameEn: 'Moray eel genus',
    commonNameBn: 'জিম্নোথোরাক্স মোরে ঈল গণ',
    description: 'Apex nocturnal ambush predators inhabiting crevice systems in tropical coral and rocky reefs.',
    isVerified: true
  },

  // --- AMPHIBIA ---
  {
    id: 'taxon-bufonidae',
    scientificName: 'Bufonidae',
    name: 'Bufonidae',
    rank: 'family',
    parentId: 'taxon-anura',
    parentTaxonId: 'taxon-anura',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1825',
    commonNameEn: 'True toads',
    commonNameBn: 'প্রকৃত কুনোব্যাঙ পরিবার',
    description: 'Warty-skinned, heavily built anurans equipped with parotoid glands secreting bufotoxins.',
    isVerified: true
  },
  {
    id: 'taxon-anaxyrus',
    scientificName: 'Anaxyrus',
    name: 'Anaxyrus',
    rank: 'genus',
    parentId: 'taxon-bufonidae',
    parentTaxonId: 'taxon-bufonidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Tschudi, 1845',
    commonNameEn: 'North American toads',
    commonNameBn: 'উত্তর আমেরিকান কুনোব্যাঙ গণ',
    description: 'Terrestrial toads with prominent cranial crests and musical breeding trills in springtime ponds.',
    isVerified: true
  },
  {
    id: 'taxon-ranidae',
    scientificName: 'Ranidae',
    name: 'Ranidae',
    rank: 'family',
    parentId: 'taxon-anura',
    parentTaxonId: 'taxon-anura',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rafinesque, 1814',
    commonNameEn: 'True frogs',
    commonNameBn: 'প্রকৃত ব্যাঙ পরিবার',
    description: 'Smooth-skinned, long-legged aquatic and riparian frogs with strong webbing on hind feet.',
    isVerified: true
  },
  {
    id: 'taxon-lithobates',
    scientificName: 'Lithobates',
    name: 'Lithobates',
    rank: 'genus',
    parentId: 'taxon-ranidae',
    parentTaxonId: 'taxon-ranidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fitzinger, 1843',
    commonNameEn: 'American water frogs',
    commonNameBn: 'আমেরিকান পানি ব্যাঙ গণ',
    description: 'Large semi-aquatic frogs with prominent dorsolateral folds and powerful jumping hindlimbs.',
    isVerified: true
  },
  {
    id: 'taxon-salamandridae',
    scientificName: 'Salamandridae',
    name: 'Salamandridae',
    rank: 'family',
    parentId: 'taxon-caudata',
    parentTaxonId: 'taxon-caudata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Goldfuss, 1820',
    commonNameEn: 'True salamanders and newts',
    commonNameBn: 'সালাম্যান্ডার ও নিউট পরিবার',
    description: 'Tailed amphibians with glandular skin often displaying bright aposematic warning coloration.',
    isVerified: true
  },
  {
    id: 'taxon-salamandra',
    scientificName: 'Salamandra',
    name: 'Salamandra',
    rank: 'genus',
    parentId: 'taxon-salamandridae',
    parentTaxonId: 'taxon-salamandridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Garsault, 1764',
    commonNameEn: 'Fire salamanders',
    commonNameBn: 'ফায়ার সালাম্যান্ডার গণ',
    description: 'Black-and-yellow aposematic forest salamanders giving birth to advanced aquatic larvae or metamorphosed young.',
    isVerified: true
  },

  // --- REPTILIA ---
  {
    id: 'taxon-viperidae',
    scientificName: 'Viperidae',
    name: 'Viperidae',
    rank: 'family',
    parentId: 'taxon-squamata',
    parentTaxonId: 'taxon-squamata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Oppel, 1811',
    commonNameEn: 'Vipers and pit vipers',
    commonNameBn: 'চন্দ্রবোড়া ও পিট ভাইপার পরিবার',
    description: 'Solenoglyphous venomous snakes with long hinged hollow fangs folding against roof of mouth.',
    isVerified: true
  },
  {
    id: 'taxon-crotalus',
    scientificName: 'Crotalus',
    name: 'Crotalus',
    rank: 'genus',
    parentId: 'taxon-viperidae',
    parentTaxonId: 'taxon-viperidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Rattlesnakes',
    commonNameBn: 'র‌্যাটলস্নেক গণ',
    description: 'New World pit vipers with infrared heat-sensing loreal facial pits and interlocking keratinous tail rattles.',
    isVerified: true
  },
  {
    id: 'taxon-boidae',
    scientificName: 'Boidae',
    name: 'Boidae',
    rank: 'family',
    parentId: 'taxon-squamata',
    parentTaxonId: 'taxon-squamata',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1825',
    commonNameEn: 'Boas',
    commonNameBn: 'বোয়া সাপ পরিবার',
    description: 'Primitive non-venomous constricting snakes retaining pelvic spurs and functional vestigial hindlimb girdles.',
    isVerified: true
  },
  {
    id: 'taxon-boa',
    scientificName: 'Boa',
    name: 'Boa',
    rank: 'genus',
    parentId: 'taxon-boidae',
    parentTaxonId: 'taxon-boidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'True boas',
    commonNameBn: 'বোয়া কনস্ট্রিক্টর গণ',
    description: 'Neotropical heavy-bodied viviparous constrictors possessing saddle markings providing camouflage.',
    isVerified: true
  },
  {
    id: 'taxon-alligatoridae',
    scientificName: 'Alligatoridae',
    name: 'Alligatoridae',
    rank: 'family',
    parentId: 'taxon-crocodylia',
    parentTaxonId: 'taxon-crocodylia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cuvier, 1807',
    commonNameEn: 'Alligators and caimans',
    commonNameBn: 'অ্যালিগেটর ও কেইম্যান পরিবার',
    description: 'Crocodilians with broad, U-shaped snouts whose lower fourth teeth fit into pits within upper jaw when closed.',
    isVerified: true
  },
  {
    id: 'taxon-alligator',
    scientificName: 'Alligator',
    name: 'Alligator',
    rank: 'genus',
    parentId: 'taxon-alligatoridae',
    parentTaxonId: 'taxon-alligatoridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Cuvier, 1807',
    commonNameEn: 'Alligators',
    commonNameBn: 'অ্যালিগেটর গণ',
    description: 'Freshwater apex predators native to temperate and subtropical wetlands in the Americas and China.',
    isVerified: true
  },

  // --- AVES ---
  {
    id: 'taxon-accipitridae',
    scientificName: 'Accipitridae',
    name: 'Accipitridae',
    rank: 'family',
    parentId: 'taxon-accipitriformes',
    parentTaxonId: 'taxon-accipitriformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Vigors, 1824',
    commonNameEn: 'Eagles, hawks, and kites',
    commonNameBn: 'ঈগল, বাজ ও চিল পরিবার',
    description: 'Diurnal birds of prey with strongly hooked beaks, sharp curved talons, and acute binocular eyesight.',
    isVerified: true
  },
  {
    id: 'taxon-haliaeetus',
    scientificName: 'Haliaeetus',
    name: 'Haliaeetus',
    rank: 'genus',
    parentId: 'taxon-accipitridae',
    parentTaxonId: 'taxon-accipitridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Savigny, 1809',
    commonNameEn: 'Sea eagles and fish eagles',
    commonNameBn: 'সিন্ধু ঈগল গণ',
    description: 'Massive piscivorous and scavenging raptors with broad wings and spiculate spiny soles for gripping slippery fish.',
    isVerified: true
  },
  {
    id: 'taxon-strigiformes',
    scientificName: 'Strigiformes',
    name: 'Strigiformes',
    rank: 'order',
    parentId: 'taxon-aves',
    parentTaxonId: 'taxon-aves',
    status: 'accepted',
    module: 'general',
    authorYear: 'Wagler, 1830',
    commonNameEn: 'Owls',
    commonNameBn: 'পেঁচা বর্গ',
    description: 'Nocturnal birds of prey with forward-facing eyes set in facial discs, asymmetrical ears, and silent flight feathers.',
    isVerified: true
  },
  {
    id: 'taxon-strigidae',
    scientificName: 'Strigidae',
    name: 'Strigidae',
    rank: 'family',
    parentId: 'taxon-strigiformes',
    parentTaxonId: 'taxon-strigiformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Leach, 1820',
    commonNameEn: 'True owls',
    commonNameBn: 'প্রকৃত পেঁচা পরিবার',
    description: 'Typical owls with round facial discs, zygodactyl talons, and dense soft plumage allowing silent hunting.',
    isVerified: true
  },
  {
    id: 'taxon-bubo',
    scientificName: 'Bubo',
    name: 'Bubo',
    rank: 'genus',
    parentId: 'taxon-strigidae',
    parentTaxonId: 'taxon-strigidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Duméril, 1805',
    commonNameEn: 'Eagle-owls and horned owls',
    commonNameBn: 'হুতুম পেঁচা গণ',
    description: 'Powerful apex nocturnal raptors possessing prominent ear tufts and immense crushing talon strength.',
    isVerified: true
  },
  {
    id: 'taxon-spheniscidae',
    scientificName: 'Spheniscidae',
    name: 'Spheniscidae',
    rank: 'family',
    parentId: 'taxon-sphenisciformes',
    parentTaxonId: 'taxon-sphenisciformes',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Bonaparte, 1831',
    commonNameEn: 'Penguins',
    commonNameBn: 'পেনগুইন পরিবার',
    description: 'Flightless marine diving birds of the Southern Hemisphere with flipper-like wings and dense insulating down.',
    isVerified: true
  },
  {
    id: 'taxon-aptenodytes',
    scientificName: 'Aptenodytes',
    name: 'Aptenodytes',
    rank: 'genus',
    parentId: 'taxon-spheniscidae',
    parentTaxonId: 'taxon-spheniscidae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'J. F. Miller, 1778',
    commonNameEn: 'Great penguins',
    commonNameBn: 'দানব পেনগুইন গণ',
    description: 'The largest penguins, characterized by bright yellow-orange auricular neck patches and extreme cold adaptations.',
    isVerified: true
  },
  {
    id: 'taxon-psittaciformes',
    scientificName: 'Psittaciformes',
    name: 'Psittaciformes',
    rank: 'order',
    parentId: 'taxon-aves',
    parentTaxonId: 'taxon-aves',
    status: 'accepted',
    module: 'general',
    authorYear: 'Wagler, 1830',
    commonNameEn: 'Parrots and macaws',
    commonNameBn: 'টিয়া ও ম্যাকাও বর্গ',
    description: 'Intelligent pantropical birds with strong curved decurved bills, prehensile muscular tongues, and zygodactyl feet.',
    isVerified: true
  },
  {
    id: 'taxon-psittacidae',
    scientificName: 'Psittacidae',
    name: 'Psittacidae',
    rank: 'family',
    parentId: 'taxon-psittaciformes',
    parentTaxonId: 'taxon-psittaciformes',
    status: 'accepted',
    module: 'general',
    authorYear: 'Rafinesque, 1815',
    commonNameEn: 'True parrots and macaws',
    commonNameBn: 'প্রকৃত তোতা ও ম্যাকাও পরিবার',
    description: 'Vibrantly plumaged arboreal birds with high encephalization quotients capable of vocal mimicry.',
    isVerified: true
  },
  {
    id: 'taxon-ara',
    scientificName: 'Ara',
    name: 'Ara',
    rank: 'genus',
    parentId: 'taxon-psittacidae',
    parentTaxonId: 'taxon-psittacidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Lacépède, 1799',
    commonNameEn: 'Macaws',
    commonNameBn: 'ম্যাকাও গণ',
    description: 'Large Neotropical parrots with long graduated tails, bare facial skin patches, and brilliant plumage.',
    isVerified: true
  },

  // --- MAMMALIA ---
  {
    id: 'taxon-felidae',
    scientificName: 'Felidae',
    name: 'Felidae',
    rank: 'family',
    parentId: 'taxon-carnivora',
    parentTaxonId: 'taxon-carnivora',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fischer von Waldheim, 1817',
    commonNameEn: 'Cats',
    commonNameBn: 'বিড়াল পরিবার',
    description: 'Obligate hypercarnivores with protractile claws, acute binocular night vision, and carnassial shear dentition.',
    isVerified: true
  },
  {
    id: 'taxon-panthera',
    scientificName: 'Panthera',
    name: 'Panthera',
    rank: 'genus',
    parentId: 'taxon-felidae',
    parentTaxonId: 'taxon-felidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Oken, 1816',
    commonNameEn: 'Roaring big cats',
    commonNameBn: 'প্যানথেরা বড় বিড়াল গণ',
    description: 'Apex big cats possessing an incompletely ossified hyoid apparatus and specialized vocal cords allowing roaring.',
    isVerified: true
  },
  {
    id: 'taxon-canidae',
    scientificName: 'Canidae',
    name: 'Canidae',
    rank: 'family',
    parentId: 'taxon-carnivora',
    parentTaxonId: 'taxon-carnivora',
    status: 'accepted',
    module: 'general',
    authorYear: 'Fischer von Waldheim, 1817',
    commonNameEn: 'Dogs, wolves, and foxes',
    commonNameBn: 'কুকুর ও নেকড়ে পরিবার',
    description: 'Cursorial social carnivorans adapted for endurance pursuit hunting with non-retractile claws and acute olfaction.',
    isVerified: true
  },
  {
    id: 'taxon-canis',
    scientificName: 'Canis',
    name: 'Canis',
    rank: 'genus',
    parentId: 'taxon-canidae',
    parentTaxonId: 'taxon-canidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'True dogs and wolves',
    commonNameBn: 'নেকড়ে ও কুকুর গণ',
    description: 'Intelligent pack-hunting carnivores displaying complex social hierarchies and vocal howling communication.',
    isVerified: true
  },
  {
    id: 'taxon-balaenopteridae',
    scientificName: 'Balaenopteridae',
    name: 'Balaenopteridae',
    rank: 'family',
    parentId: 'taxon-cetacea',
    parentTaxonId: 'taxon-cetacea',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Gray, 1864',
    commonNameEn: 'Rorquals',
    commonNameBn: 'রোরকোয়াল তিমি পরিবার',
    description: 'Baleen whales with expandable longitudinal throat pleats engulfing massive volumes of krill-laden seawater.',
    isVerified: true
  },
  {
    id: 'taxon-balaenoptera',
    scientificName: 'Balaenoptera',
    name: 'Balaenoptera',
    rank: 'genus',
    parentId: 'taxon-balaenopteridae',
    parentTaxonId: 'taxon-balaenopteridae',
    status: 'accepted',
    module: 'marine',
    authorYear: 'Lacépède, 1804',
    commonNameEn: 'Rorqual genus',
    commonNameBn: 'রোরকোয়াল গণ',
    description: 'Slender, streamlined pelagic rorquals including the largest animals ever known to inhabit Earth.',
    isVerified: true
  },
  {
    id: 'taxon-hominidae',
    scientificName: 'Hominidae',
    name: 'Hominidae',
    rank: 'family',
    parentId: 'taxon-primates',
    parentTaxonId: 'taxon-primates',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1825',
    commonNameEn: 'Great apes',
    commonNameBn: 'বৃহৎ নরবানর পরিবার',
    description: 'Large, tailless catarrhine primates with high cognitive complexity, tool-making abilities, and complex social cultures.',
    isVerified: true
  },
  {
    id: 'taxon-gorilla',
    scientificName: 'Gorilla',
    name: 'Gorilla',
    rank: 'genus',
    parentId: 'taxon-hominidae',
    parentTaxonId: 'taxon-hominidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'I. Geoffroy Saint-Hilaire, 1852',
    commonNameEn: 'Gorillas',
    commonNameBn: 'গরিলা গণ',
    description: 'Ground-dwelling, predominantly herbivorous African apes that knuckle-walk through equatorial rainforests.',
    isVerified: true
  },
  {
    id: 'taxon-pteropodidae',
    scientificName: 'Pteropodidae',
    name: 'Pteropodidae',
    rank: 'family',
    parentId: 'taxon-chiroptera',
    parentTaxonId: 'taxon-chiroptera',
    status: 'accepted',
    module: 'general',
    authorYear: 'Gray, 1821',
    commonNameEn: 'Fruit bats / Flying foxes',
    commonNameBn: 'ফলভোজী বাদুড় পরিবার',
    description: 'Megachiropterans feeding on fruit, nectar, and pollen, using large eyes and acute smell rather than echolocation.',
    isVerified: true
  },
  {
    id: 'taxon-pteropus',
    scientificName: 'Pteropus',
    name: 'Pteropus',
    rank: 'genus',
    parentId: 'taxon-pteropodidae',
    parentTaxonId: 'taxon-pteropodidae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Brisson, 1762',
    commonNameEn: 'Flying foxes',
    commonNameBn: 'উড়ন্ত শিয়াল / বড় বাদুড় গণ',
    description: 'Canine-faced giant fruit bats with massive wingspans performing critical forest pollination and seed dispersal.',
    isVerified: true
  },
  {
    id: 'taxon-castoridae',
    scientificName: 'Castoridae',
    name: 'Castoridae',
    rank: 'family',
    parentId: 'taxon-rodentia',
    parentTaxonId: 'taxon-rodentia',
    status: 'accepted',
    module: 'general',
    authorYear: 'Hemprich, 1820',
    commonNameEn: 'Beavers',
    commonNameBn: 'বিভার পরিবার',
    description: 'Semiaquatic rodents equipped with broad scaly tails, iron-rich orange incisors, and keystone dam-building habits.',
    isVerified: true
  },
  {
    id: 'taxon-castor',
    scientificName: 'Castor',
    name: 'Castor',
    rank: 'genus',
    parentId: 'taxon-castoridae',
    parentTaxonId: 'taxon-castoridae',
    status: 'accepted',
    module: 'general',
    authorYear: 'Linnaeus, 1758',
    commonNameEn: 'Beaver genus',
    commonNameBn: 'বিভার গণ',
    description: 'Ecosystem engineers constructing elaborate lodges and wetlands regulating riparian hydrology.',
    isVerified: true
  }
];

console.log(`Prepared ${NEW_TAXA_NODES.length} new taxonomic nodes across all 13 priority groups.`);

module.exports = { NEW_TAXA_NODES };
