// BiotaElite 2.0 About & Scientific Methodology Page
import React from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { Breadcrumbs } from '../../components/common/Breadcrumbs';
import { BackButton } from '../../components/common/BackButton';
import { ShieldCheck, BookOpen, Compass, Lock } from 'lucide-react';

export const AboutPage: React.FC = () => {
  const { t, language } = useLanguage();

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem', flexWrap: 'wrap', gap: '0.75rem' }}>
        <BackButton fallbackPath="/species" />
        <Breadcrumbs items={[{ label: t('crumb.about') }]} />
      </div>

      <div style={{ marginBottom: '2.5rem' }}>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', color: 'var(--accent-emerald-light)', fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>
          <Compass size={16} />
          <span>{t('about.portalTitle')}</span>
        </div>

        <h1 style={{ fontSize: 'clamp(1.8rem, 3.5vw, 2.5rem)', fontWeight: 800, color: '#ffffff', marginBottom: '0.75rem' }}>
          {language === 'bn' ? 'বায়োটাএলিট ২.০ পরিচিতি' : 'About BiotaElite 2.0'}
        </h1>

        <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem', maxWidth: '850px', lineHeight: '1.7' }}>
          {language === 'bn'
            ? 'বায়োটাএলিট ২.০ একটি প্রাতিষ্ঠানিক বৈজ্ঞানিক জীববৈচিত্র্য তথ্য প্ল্যাটফর্ম, যা গবেষক, সংরক্ষণবিদ, ট্যাক্সোনমিস্ট এবং বিজ্ঞান সম্প্রদায়ের জন্য নিবেদিত। এটি আঞ্চলিক জীববৈচিত্র্য সাহিত্য ও আধুনিক স্কেলযোগ্য ডেটা আর্কিটেকচারের সমন্বয় সাধন করে।'
            : 'BiotaElite 2.0 is an enterprise biodiversity information platform designed for researchers, conservationists, taxonomists, educators, and the scientific community. Our platform bridges the gap between fragmented regional biodiversity literature and modern scalable data architectures.'}
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '2rem', marginBottom: '3rem' }}>
        {/* Core Principles */}
        <div className="card">
          <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: 'rgba(16, 185, 129, 0.15)', color: '#34d399', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}>
            <ShieldCheck size={22} />
          </div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '0.5rem' }}>
            {language === 'bn' ? 'শূন্য কল্পিত বিজ্ঞান (Zero Fabricated Science)' : 'Zero Fabricated Science'}
          </h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: '1.6' }}>
            {language === 'bn'
              ? 'আমাদের মূল চার্টার অনুসারে, কোনো বৈজ্ঞানিক তথ্য বা দ্বিপদ নাম কাল্পনিক অনুমান বা অপ্রমাণিত কৃত্রিম বুদ্ধিমত্তা দ্বারা তৈরি হয় না। কোনো বৈশিষ্ট্য অপ্রাপ্য হলে তা সততার সাথে অজানা হিসেবে চিহ্নিত করা হয়।'
              : 'In accordance with our core charter, no scientific facts or binomial names are generated by speculation or unverified AI output. When a zoological trait or geographic record is uncertain or unavailable, it is explicitly cataloged as unverified or unknown.'}
          </p>
        </div>

        <div className="card">
          <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: 'rgba(2, 132, 199, 0.15)', color: '#38bdf8', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}>
            <BookOpen size={22} />
          </div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '0.5rem' }}>
            {language === 'bn' ? 'কঠোর আইসিজেডএন অনুসরণ' : 'Strict ICZN Adherence'}
          </h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: '1.6' }}>
            {language === 'bn'
              ? 'সমস্ত ট্যাক্সোনমিক নাম আন্তর্জাতিক প্রাণিবিজ্ঞান নামকরণ বিধিমালা (ICZN) মেনে চলে। দ্বিপদ নামগুলি কঠোরভাবে ওপেন সানস ইটালিকে প্রদর্শিত হয় এবং লেখক ও বছর স্বাভাবিক ফন্টে থাকে।'
              : 'All taxonomic names follow the International Code of Zoological Nomenclature (ICZN). Binomial names are strictly styled in Open Sans Italic without decorative typography, while original authorship and years are rendered in roman typeface.'}
          </p>
        </div>

        <div className="card">
          <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: 'rgba(217, 119, 6, 0.15)', color: '#fbbf24', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}>
            <Lock size={22} />
          </div>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ffffff', marginBottom: '0.5rem' }}>
            {language === 'bn' ? 'পৃথক যাচাইকরণ লাইফসাইকেল' : 'Decoupled Verification Lifecycle'}
          </h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: '1.6' }}>
            {language === 'bn'
              ? '"যাচাইকৃত" (Verified) এবং "প্রকাশিত" (Published) সম্পূর্ণ আলাদা পর্যায়। কঠোর সমকক্ষ পর্যালোচনার পরেই কেবলমাত্র একটি রেকর্ড সাধারণ মানুষের জন্য উন্মুক্ত পোর্টালে প্রদর্শিত হয়।'
              : '"Verified" and "Published" are completely separate lifecycle states. A record undergoes formal peer review before verification, and only verified, approved records are surfaced to the public portal.'}
          </p>
        </div>
      </div>

      {/* Methodology Section */}
      <section className="card" style={{ padding: '2.5rem', background: 'var(--bg-surface)' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#ffffff', marginBottom: '1rem' }}>
          {language === 'bn' ? 'যাচাইকরণ ও পিয়ার-রিভিউ কার্যপদ্ধতি' : 'Verification & Peer-Review Methodology'}
        </h2>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', color: 'var(--text-secondary)', fontSize: '0.95rem', lineHeight: '1.7' }}>
          <p>
            {language === 'bn'
              ? 'ট্যাক্সোনমিক এন্ট্রিগুলো পিয়ার-রিভিউড বৈজ্ঞানিক সাহিত্য (মনোগ্রাফ, জার্নাল), স্বীকৃত বৈশ্বিক ডাটাবেস (Catalog of Fishes, WoRMS, FishBase), অথবা সরকারি সংরক্ষণ মূল্যায়ন (যেমন: IUCN বাংলাদেশ রেড লিস্ট ২০১৫) থেকে সংগৃহীত।'
              : 'Taxonomic entries originate from peer-reviewed scientific literature (monographs, journals), authoritative global databases (Catalog of Fishes, WoRMS, FishBase), or verified government conservation assessments (e.g. IUCN Bangladesh Red List 2015).'}
          </p>

          <div style={{ background: 'var(--bg-card)', padding: '1.25rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)', marginTop: '0.5rem' }}>
            <h4 style={{ color: 'var(--accent-emerald-light)', fontSize: '0.95rem', marginBottom: '0.5rem' }}>
              {language === 'bn' ? 'তথ্য প্রশাসন পাইপলাইন' : 'Data Governance Pipeline'}
            </h4>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap', fontSize: '0.85rem' }}>
              <span className="badge" style={{ background: 'rgba(100, 116, 139, 0.2)', color: '#94a3b8' }}>1. Draft (খসড়া)</span>
              <span>→</span>
              <span className="badge" style={{ background: 'rgba(217, 119, 6, 0.2)', color: '#fbbf24' }}>2. Under Review (পর্যালোচনাধীন)</span>
              <span>→</span>
              <span className="badge" style={{ background: 'rgba(2, 132, 199, 0.2)', color: '#38bdf8' }}>3. Peer-Verified (যাচাইকৃত)</span>
              <span>→</span>
              <span className="badge" style={{ background: 'rgba(16, 185, 129, 0.2)', color: '#34d399' }}>4. Published (প্রকাশিত)</span>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};
